import { chromium } from 'playwright-core';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';

const baseURL=process.env.MICROSCOPY_URL || 'http://127.0.0.1:8765',output=path.resolve('test-artifacts',`xray-${Date.now()}`);await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.MICROSCOPY_CHROME_PATH?{executablePath:process.env.MICROSCOPY_CHROME_PATH}:{}),args:['--enable-unsafe-swiftshader']}),context=await browser.newContext({acceptDownloads:true,viewport:{width:1600,height:1350}}),page=await context.newPage(),errors=[],submissions=[];
page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(request.method()==='POST'&&request.url().endsWith('/api/v2/jobs'))submissions.push(request.postDataJSON());});
const waitView=()=>page.waitForFunction(()=>document.querySelector('#xpv-view-note')?.textContent.startsWith('Reading saved data only')&&Number(document.querySelector('#xpv-projection').dataset.rows)>0,{},{timeout:120000});
const responseFor=(suffix,method='GET')=>page.waitForResponse(response=>response.url().includes(suffix)&&response.request().method()===method,{timeout:120000});
const noOverflow=()=>page.evaluate(()=>{const d=document.querySelector('#xpv-dialog'),l=document.querySelector('.xpv-layout');return d.scrollWidth<=d.clientWidth+2&&l.scrollWidth<=l.clientWidth+2&&document.documentElement.scrollWidth<=innerWidth+2;});
let datasetId;
try{
  await page.goto(`${baseURL}/?specimen=nvidia-h100-sxm`,{waitUntil:'networkidle'});await page.waitForFunction(()=>document.querySelector('#example-picker')?.value==='nvidia-h100-sxm'&&!document.querySelector('#example-picker').disabled,{},{timeout:60000});
  await page.locator('#roi-site').selectOption('hbm-6');await page.locator('#roi-stack').click();await page.locator('#xray-volumes-btn').click();assert.match(await page.locator('#xpv-snapshot').innerText(),/Full specimen.*acoustic ROI does not crop/s);
  for(const [id,value] of [['views',8],['geometry_nx',32],['geometry_ny',32],['geometry_nz',256],['detector_cols',48],['detector_rows',32],['photons',1000]])await page.locator(`#xpv-${id}`).fill(String(value));
  await page.locator('#xpv-noise').check();await page.locator('#xpv-estimate-btn').click();await page.waitForFunction(()=>!document.querySelector('#xpv-start').disabled);assert.match(await page.locator('#xpv-estimate').innerText(),/8 × 32 × 48/);
  const submitting=responseFor('/api/v2/jobs','POST');await page.locator('#xpv-start').click();const response=await submitting;assert.equal(response.status(),202);const job=await response.json();datasetId=job.dataset_id;assert.equal(submissions.at(-1).kind,'xray_projection_volume');assert(!Object.hasOwn(submissions.at(-1).acquisition,'roi_mm'));
  await page.locator(`.xpv-dataset[data-dataset-id="${datasetId}"]:not(:disabled)`).waitFor({timeout:120000});await page.locator(`.xpv-dataset[data-dataset-id="${datasetId}"]`).click();await waitView();
  const initial=await (await context.request.get(`${baseURL}/api/v2/datasets/${datasetId}/xray-view?view_index=0&detector_row=16&product=transmission`)).json();assert.equal(initial.cursor.angle_deg,0);assert.deepEqual(initial.sinogram.angles_deg,[0,45,90,135,180,225,270,315]);assert.equal(initial.projection.image.length,32);assert.equal(initial.projection.image[0].length,48);assert(initial.projection.extent_mm[0]<0);assert.equal(initial.sinogram.image.length,8);
  const beforeBrowsing=submissions.length;let waiting=responseFor(`/api/v2/datasets/${datasetId}/xray-view?`);await page.locator('#xpv-view').evaluate(element=>{element.value='2';element.dispatchEvent(new Event('input',{bubbles:true}));});const orthogonal=await (await waiting).json();await waitView();assert.equal(orthogonal.cursor.angle_deg,90);assert.notDeepEqual(orthogonal.projection.image,initial.projection.image);assert(Math.abs(initial.pose.ray_direction_xyz.reduce((sum,v,i)=>sum+v*orthogonal.pose.ray_direction_xyz[i],0))<1e-12);
  waiting=responseFor(`/api/v2/datasets/${datasetId}/xray-view?`);await page.locator('#xpv-row').evaluate(element=>{element.value='9';element.dispatchEvent(new Event('input',{bubbles:true}));});const row=await (await waiting).json();await waitView();assert.equal(row.cursor.detector_row,9);assert.deepEqual(row.profile.values,row.projection.image[9]);assert.deepEqual(row.sinogram.image[row.cursor.view_index],row.projection.image[9]);
  waiting=responseFor(`/api/v2/datasets/${datasetId}/xray-view?`);await page.locator('#xpv-product').selectOption('line_integrals');const logs=await (await waiting).json();await waitView();assert.equal(logs.product,'line_integrals');assert.equal(await page.locator('#xpv-window').inputValue(),'4');assert(logs.projection.invalid_mask.flat().every(value=>typeof value==='boolean'));assert.match(await page.locator('#xpv-invalid-count').innerText(),/zero-count.*logarithms are undefined/);
  waiting=responseFor(`/api/v2/datasets/${datasetId}/xray-view?`);await page.locator('#xpv-product').selectOption('counts');const counts=await (await waiting).json();await waitView();assert.equal(await page.locator('#xpv-window').inputValue(),'1000');assert.equal(counts.profile.unit,'photon counts');for(let j=0;j<counts.profile.values.length;j++)assert(Math.abs(counts.profile.values[j]/1000-row.profile.values[j])<1e-6);assert.equal(submissions.length,beforeBrowsing,'Scrubbing and product selection must not submit acquisitions.');
  waiting=responseFor(`/api/v2/datasets/${datasetId}/xray-view?`);await page.locator('#xpv-product').selectOption('transmission');await waiting;await waitView();await page.locator('#xpv-view').evaluate(element=>{element.value='0';element.dispatchEvent(new Event('input',{bubbles:true}));});await page.waitForFunction(()=>document.querySelector('#xpv-angle-value').textContent.startsWith('0°'));await page.screenshot({path:path.join(output,'xray-projection-workspace.png')});assert(await noOverflow());
  const downloaded=page.waitForEvent('download');await page.locator('#xpv-export').click();const download=await downloaded,destination=path.join(output,'xray-projections.zip');await download.saveAs(destination);assert.equal(await download.failure(),null);assert.equal((await readFile(destination)).subarray(0,2).toString(),'PK');
  const catalog=(await (await context.request.get(`${baseURL}/api/v2/datasets`)).json()).datasets,xrayIds=new Set(catalog.filter(d=>d.kind==='xray_projection_volume').map(d=>d.dataset_id || d.id));await page.locator('#xpv-close').click();await page.locator('#volumes-btn').click();await page.waitForFunction(()=>!document.querySelector('#vol-datasets').textContent.includes('Loading saved'));
  const listed=await page.locator('#vol-datasets .vol-dataset').evaluateAll(elements=>elements.map(element=>element.dataset.datasetId));assert(listed.every(id=>!xrayIds.has(id)),'SAM catalog must exclude X-ray projection datasets.');const sam=catalog.find(d=>d.kind==='sam_rf_volume'&&d.complete);if(sam){assert(listed.includes(sam.dataset_id || sam.id));await page.locator(`.vol-dataset[data-dataset-id="${sam.dataset_id || sam.id}"]`).click();await page.waitForFunction(()=>document.querySelector('#vol-view-note').textContent.startsWith('Reading saved data only'),{},{timeout:90000});}
  await page.locator('#vol-close').click();await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>document.querySelector('#example-picker')?.value==='nvidia-h100-sxm'&&!document.querySelector('#example-picker').disabled,{},{timeout:60000});await page.locator('#xray-volumes-btn').click();await waitView();assert.equal(await page.locator('#xpv-export').getAttribute('href'),`/api/v2/datasets/${datasetId}/export`);assert.equal(submissions.length,beforeBrowsing);
  const xrayListed=await page.locator('#xpv-datasets .xpv-dataset').evaluateAll(elements=>elements.map(element=>element.dataset.datasetId));assert(xrayListed.every(id=>xrayIds.has(id)),'X-ray catalog must exclude acoustic datasets.');
  await page.setViewportSize({width:390,height:844});await page.locator('#xpv-new-panel').evaluate(element=>element.open=false);await page.locator('#xpv-viewer').scrollIntoViewIfNeeded();assert(await noOverflow());await page.screenshot({path:path.join(output,'xray-projection-mobile.png')});assert.deepEqual(errors,[]);
  await writeFile(path.join(output,'verification.json'),JSON.stringify({passed:true,datasetId,shape:[8,32,48],angles:initial.sinogram.angles_deg,checks:['full specimen preserved despite SAM ROI','independent geometry and detector sampling','0 and 90 degree distinct projections and orthogonal ray directions','profile and sinogram coordinate consistency','three saved numerical products and invalid mask semantics','no projector jobs from scrubbing','native Zarr ZIP download','persistent reload','mixed SAM/X-ray catalog separation','desktop/mobile layout'],errors},null,2));console.log(`X-ray volume verification passed: ${output}`);
}catch(error){await page.screenshot({path:path.join(output,'failure.png')}).catch(()=>{});await writeFile(path.join(output,'failure.json'),JSON.stringify({error:error.stack,datasetId,errors},null,2));throw error;}finally{await browser.close();}
