import { chromium } from 'playwright-core';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';

const baseURL=process.env.MICROSCOPY_URL||'http://127.0.0.1:8765',output=path.resolve('test-artifacts',`depth-${Date.now()}`);await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.MICROSCOPY_CHROME_PATH?{executablePath:process.env.MICROSCOPY_CHROME_PATH}:{}),args:['--enable-unsafe-swiftshader']}),context=await browser.newContext({acceptDownloads:true,viewport:{width:1600,height:1450}}),page=await context.newPage(),errors=[],submissions=[];
page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(request.method()==='POST'&&request.url().endsWith('/api/v2/jobs'))submissions.push(request.postDataJSON());});
const responseFor=(suffix,method='GET')=>page.waitForResponse(response=>response.url().includes(suffix)&&response.request().method()===method,{timeout:120000});
const waitView=()=>page.waitForFunction(()=>document.querySelector('#depth-view-note')?.textContent.startsWith('Reading saved data only')&&Number(document.querySelector('#depth-xy').dataset.rows)>0,{},{timeout:120000});
const noOverflow=()=>page.evaluate(()=>{const dialog=document.querySelector('#depth-dialog'),layout=document.querySelector('.depth-layout');return dialog.scrollWidth<=dialog.clientWidth+2&&layout.scrollWidth<=layout.clientWidth+2&&document.documentElement.scrollWidth<=innerWidth+2;});
const near=(actual,expected)=>assert(Math.abs(actual-expected)<1e-8,`${actual} != ${expected}`);
const sliders=values=>page.evaluate(values=>{for(const [axis,value] of Object.entries(values)){const slider=document.querySelector(`#depth-${axis}`);slider.value=value;slider.dispatchEvent(new Event('input',{bubbles:true}));}},values);
let sourceId,datasetId;
try{
  const twin={name:'Synthetic SAM depth verification package',description:'Known synthetic geometry for browser QA; mapping velocities remain user-assumed.',size_mm:[3,2,2],objects:[{id:'epoxy',name:'Epoxy body',shape:'box',material:'epoxy',center_mm:[1.5,1,1],size_mm:[3,2,2]},{id:'silicon',name:'Silicon insert',shape:'box',material:'silicon',center_mm:[1.4,.8,.65],size_mm:[1.2,.8,.5]},{id:'copper',name:'Copper insert',shape:'box',material:'copper',center_mm:[2.4,1.4,1.3],size_mm:[.4,.4,.2]}]};
  const created=await context.request.post(`${baseURL}/api/v2/jobs`,{data:{twin,acquisition:{scan_nx:20,scan_ny:16,depth_samples:256,roi_mm:[.5,.25,2.5,1.75],frequency_mhz:20,fractional_bandwidth:.6,focus_mm:.65,record_start_us:.1,record_duration_us:1,sample_rate_mhz:200,water_standoff_mm:.1,include_defects:true}}});assert.equal(created.status(),202,await created.text());const source=await created.json();sourceId=source.dataset_id;
  const deadline=Date.now()+120000;let sourceJob;do{sourceJob=await (await context.request.get(`${baseURL}/api/v2/jobs/${source.id}`)).json();assert(!['failed','cancelled'].includes(sourceJob.status),sourceJob.error);if(sourceJob.status==='completed')break;await new Promise(resolve=>setTimeout(resolve,350));}while(Date.now()<deadline);assert.equal(sourceJob.status,'completed');
  await page.goto(`${baseURL}/?specimen=nvidia-h100-sxm`,{waitUntil:'networkidle'});await page.waitForFunction(()=>document.querySelector('#example-picker')?.value==='nvidia-h100-sxm'&&!document.querySelector('#example-picker').disabled,{},{timeout:60000});await page.locator('#sam-depth-btn').click();await page.locator(`#depth-source option[value="${sourceId}"]`).waitFor({state:'attached',timeout:60000});await page.locator('#depth-source').selectOption(sourceId);await page.waitForFunction(id=>document.querySelector('#depth-source-detail').textContent.includes(id)&&!document.querySelector('#depth-start').disabled,sourceId,{timeout:60000});assert.match(await page.locator('#depth-source-detail').innerText(),/Saved X\/Y raster 20 × 16/);assert.equal(await page.locator('#depth-model_evidence').inputValue(),'user_assumed');assert(await page.locator('#depth-surface_time_us').isDisabled());const waterTime=Number(await page.locator('#depth-surface_time_us').inputValue());assert(waterTime>.1&&waterTime<.2);
  await page.locator('#depth-z_max_mm').fill('1.8');await page.locator('#depth-nz').fill('128');await page.locator('#depth-surface_reference').selectOption('explicit');await page.locator('#depth-surface_time_us').fill('.08');await page.locator('#depth-velocity_model').selectOption('layered');const first=page.locator('.depth-layer').nth(0);await first.locator('[data-field="end"]').fill('.4');await first.locator('[data-field="speed"]').fill('5000');await page.locator('#depth-add-layer').click();const second=page.locator('.depth-layer').nth(1);await second.locator('[data-field="end"]').fill('1.2');await second.locator('[data-field="speed"]').fill('6500');await page.locator('#depth-model_note').fill('QA user assumption: explicit original-axis time and two declared velocities; model ends before output bounds.');await page.locator('#depth-estimate-btn').click();await page.waitForFunction(()=>!document.querySelector('#depth-start').disabled,{},{timeout:90000});assert.match(await page.locator('#depth-estimate').innerText(),/128 × 16 × 20/);assert.match(await page.locator('#depth-warnings').textContent(),/not extrapolated|cover only/);
  const submitting=responseFor('/api/v2/jobs','POST');await page.locator('#depth-start').click();const response=await submitting;assert.equal(response.status(),202);const job=await response.json();datasetId=job.dataset_id;const sent=submissions.at(-1);assert.equal(sent.kind,'sam_depth_volume');assert.equal(sent.source_dataset_id,sourceId);assert(!Object.hasOwn(sent,'twin'));assert.equal(sent.mapping.surface_time_us,.08);assert.equal(sent.mapping.model_evidence,'user_assumed');assert.deepEqual(sent.mapping.layers,[{end_depth_mm:.4,sound_speed_m_s:5000},{end_depth_mm:1.2,sound_speed_m_s:6500}]);
  await page.locator(`.depth-dataset[data-dataset-id="${datasetId}"]:not(:disabled)`).waitFor({timeout:120000});await page.locator(`.depth-dataset[data-dataset-id="${datasetId}"]`).click();await waitView();const submittedCount=submissions.length;
  let waiting=responseFor(`/api/v2/datasets/${datasetId}/depth-view?x_index=3&y_index=5&z_index=40&product=rf`);await sliders({x:3,y:5,z:40});const view=await (await waiting).json();await waitView();assert.deepEqual(view.metadata.shape,[128,16,20]);assert.deepEqual(view.metadata.axis_order,['z','y','x']);assert.equal(view.xy.image.length,16);assert.equal(view.xy.image[0].length,20);assert.equal(view.xz.image.length,128);assert.equal(view.yz.image[0].length,16);near(view.cursor.x_mm,.5+3.5*2/20);near(view.cursor.y_mm,.25+5.5*1.5/16);near(view.cursor.z_mm,40.5*1.8/128);near(view.cursor.sample_time_us,.08+2*.4/5+2*(view.cursor.z_mm-.4)/6.5);assert.equal(view.cursor.valid,true);assert.equal(view.xy.image[5][3],view.cursor.rf);assert.equal(view.xz.image[40][3],view.cursor.rf);assert.equal(view.yz.image[40][5],view.cursor.rf);assert.equal(view.metadata.model_evidence,'user_assumed');const signals=view.xz.image.flat();assert(signals.some(value=>value>1e-6)&&signals.some(value=>value<-1e-6),'Depth RF must preserve both signed polarities.');
  waiting=responseFor(`/api/v2/datasets/${datasetId}/depth-view?x_index=3&y_index=5&z_index=100&product=rf`);await sliders({z:100});const unsupported=await (await waiting).json();await waitView();assert.equal(unsupported.cursor.model_valid,false);assert.equal(unsupported.cursor.valid,false);assert.equal(unsupported.cursor.sample_time_us,null);assert.equal(unsupported.cursor.rf,0);assert(unsupported.xy.valid_mask.flat().every(value=>value===false));assert.match(await page.locator('#depth-cursor-time').innerText(),/unavailable beyond the velocity model/);assert.match(await page.locator('#depth-cursor-signal').innerText(),/masked/);const maskColor=await page.locator('#depth-xy').evaluate(canvas=>{const p=canvas._depthPlot,dpr=canvas.width/canvas.clientWidth;return [...canvas.getContext('2d').getImageData(Math.floor((p.left+p.width*.025)*dpr),Math.floor((p.top+p.height*.03125)*dpr),1,1).data].slice(0,3);});assert.deepEqual(maskColor,[136,147,157]);
  waiting=responseFor(`/api/v2/datasets/${datasetId}/depth-view?x_index=3&y_index=5&z_index=0&product=rf`);await sliders({z:0});const beforeRecord=await (await waiting).json();await waitView();assert.equal(beforeRecord.cursor.model_valid,true);assert.equal(beforeRecord.cursor.valid,false);assert(beforeRecord.cursor.sample_time_us<.1);assert.match(await page.locator('#depth-cursor-valid').innerText(),/Outside recorded time/);
  const peak=view.profiles.z.values.reduce((best,value,index,values)=>Math.abs(value)>Math.abs(values[best])?index:best,0);waiting=responseFor(`/api/v2/datasets/${datasetId}/depth-view?x_index=3&y_index=5&z_index=${peak}&product=rf`);await sliders({z:peak});await waiting;await waitView();const location=await page.locator('#depth-xy').evaluate(canvas=>{const p=canvas._depthPlot;return {x:p.left+p.width*.725,y:p.top+p.height*.40625};});waiting=responseFor(`/api/v2/datasets/${datasetId}/depth-view?x_index=14&y_index=6&z_index=${peak}&product=rf`);await page.locator('#depth-xy').click({position:location});await waiting;await waitView();waiting=responseFor(`/api/v2/datasets/${datasetId}/depth-view?x_index=14&y_index=6&z_index=${Math.max(0,peak-1)}&product=rf`);await page.locator('#depth-xz').focus();await page.keyboard.press('ArrowUp');await waiting;await waitView();
  waiting=responseFor(`/api/v2/datasets/${datasetId}/depth-view?`);await page.locator('#depth-product').selectOption('envelope');const envelope=await (await waiting).json();await waitView();assert.equal(envelope.metadata.product,'envelope');assert(envelope.xz.image.flat().every(value=>value>=0));assert.equal(await page.locator('#depth-window-min').inputValue(),'0');waiting=responseFor(`/api/v2/datasets/${datasetId}/depth-view?`);await page.locator('#depth-product').selectOption('rf');await waiting;await waitView();await page.locator('#depth-window-min').fill('-.000001');await page.locator('#depth-window-max').fill('.000002');assert.equal(await page.locator('#depth-window-low').innerText(),'-1.000e-6');assert.equal(await page.locator('#depth-window-high').innerText(),'2.000e-6');await page.locator('#depth-window-min').fill('-.2');await page.locator('#depth-window-max').fill('.2');assert.equal(await page.locator('#depth-window-low').innerText(),'-0.2');assert.equal(submissions.length,submittedCount,'Saved-data scrubbing and display limits must not submit jobs.');assert(await noOverflow());await page.screenshot({path:path.join(output,'sam-depth-workspace.png')});
  const downloaded=page.waitForEvent('download');await page.locator('#depth-export').click();const download=await downloaded,destination=path.join(output,'sam-depth.zip');await download.saveAs(destination);assert.equal(await download.failure(),null);assert.equal((await readFile(destination)).subarray(0,2).toString(),'PK');
  const catalog=(await (await context.request.get(`${baseURL}/api/v2/datasets`)).json()).datasets,depthIds=new Set(catalog.filter(item=>item.kind==='sam_depth_volume').map(item=>item.dataset_id||item.id));assert((await page.locator('#depth-datasets .depth-dataset').evaluateAll(elements=>elements.map(element=>element.dataset.datasetId))).every(id=>depthIds.has(id)));const sourceIds=await page.locator('#depth-source option').evaluateAll(options=>options.map(option=>option.value).filter(Boolean));assert(sourceIds.every(id=>catalog.some(item=>(item.dataset_id||item.id)===id&&item.kind==='sam_rf_volume')));await page.locator('#depth-close').click();
  for(const [button,dialog,list,item] of [['volumes-btn','vol','vol-datasets','.vol-dataset'],['xray-volumes-btn','xpv','xpv-datasets','.xpv-dataset'],['reconstruction-btn','ct','ct-datasets','.ct-dataset']]){await page.locator(`#${button}`).click();await page.waitForFunction(id=>Boolean(document.querySelector(`#${id}`)?.textContent.trim().length),list);const listed=await page.locator(`#${list} ${item}`).evaluateAll(elements=>elements.map(element=>element.dataset.datasetId));assert(listed.every(id=>!depthIds.has(id)),`${dialog} must exclude SAM depth datasets`);await page.locator(`#${dialog}-close`).click();}
  await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>document.querySelector('#example-picker')?.value==='nvidia-h100-sxm'&&!document.querySelector('#example-picker').disabled,{},{timeout:60000});await page.locator('#sam-depth-btn').click();await waitView();assert.equal(await page.locator('#depth-export').getAttribute('href'),`/api/v2/datasets/${datasetId}/export`);assert.match(await page.locator('#depth-saved-model').innerText(),/User-assumed model.*5,?000.*6,?500/);assert.equal(submissions.length,submittedCount);
  await page.setViewportSize({width:390,height:844});await page.locator('#depth-new-panel').evaluate(element=>element.open=false);await page.locator('#depth-xy').scrollIntoViewIfNeeded();assert(await noOverflow());await page.screenshot({path:path.join(output,'sam-depth-mobile.png')});assert.deepEqual(errors,[]);
  await writeFile(path.join(output,'verification.json'),JSON.stringify({passed:true,sourceId,datasetId,shape:[128,16,20],surface_time_us:.08,checks:['native saved-source mapping independent of current H100 preview','source ROI and X/Y sampling preserved','water delay default and explicit original-axis time','two user-assumed velocity layers','linked physical slices and keyboard cursor','RF positive/negative polarities and nonnegative envelope','outside-model null travel time and gray masked placeholders','outside-record masked samples with model time retained','negative display window without new jobs','native Zarr ZIP export','all four catalogs isolated by kind','persistent model/source reload','desktop/mobile layout'],errors},null,2));console.log(`SAM depth verification passed: ${output}`);
}catch(error){await page.screenshot({path:path.join(output,'failure.png')}).catch(()=>{});await writeFile(path.join(output,'failure.json'),JSON.stringify({error:error.stack,sourceId,datasetId,errors},null,2));throw error;}finally{await browser.close();}
