import { chromium } from 'playwright-core';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';

const baseURL=process.env.MICROSCOPY_URL || 'http://127.0.0.1:8765';
const output=path.resolve('test-artifacts',`hbm-${Date.now()}`);await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.MICROSCOPY_CHROME_PATH?{executablePath:process.env.MICROSCOPY_CHROME_PATH}:{}),args:['--enable-unsafe-swiftshader']});
const context=await browser.newContext({acceptDownloads:true,viewport:{width:1600,height:1200}});
const page=await context.newPage(),errors=[],probeRequests=[];page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(request.url().endsWith('/api/probe'))probeRequests.push(request);});
const responseFor=route=>page.waitForResponse(response=>response.url().endsWith(route),{timeout:60000});
const complete=()=>page.locator('#acquisition-status').filter({hasText:'Acquisition complete'}).waitFor({timeout:60000});
const sectionReady=()=>page.waitForFunction(()=>document.querySelector('#hbm-section-loading').hidden && Number(document.querySelector('#hbm-section').dataset.materialCount)>1);
const download=async(selector,name)=>{const waiting=page.waitForEvent('download');await page.locator(selector).click();const file=await waiting,destination=path.join(output,name);await file.saveAs(destination);assert.equal(await file.failure(),null);return JSON.parse(await readFile(destination,'utf8'));};
const apply=async()=>{const response=responseFor('/api/hbm/compose');await page.locator('#hbm-apply').click();const result=await response;return {response:result,data:await result.json()};};
const close=async()=>{await page.locator('#hbm-close').click();};
const open=async()=>{await page.locator('#hbm-editor-btn').click();await sectionReady();};
try {
  await page.goto(`${baseURL}/?specimen=nvidia-h100-sxm`,{waitUntil:'networkidle'});await complete();
  assert.equal(await page.locator('.scene-part-label').count(),7);
  const original=await download('#export-twin','original.json');assert.equal(original.hbm_assemblies.length,6);assert(original.hbm_assemblies.every(item=>item.physical_present));
  assert.equal(await page.locator('#depth-samples').inputValue(),'','Legacy acquisition keeps automatic depth sampling.');
  await open();assert.equal(await page.locator('#hbm-site option').count(),6);assert.equal(await page.locator('#hbm-die_count').inputValue(),'8');assert.equal(await page.locator('#hbm-total-thickness').innerText(),'620 µm');
  await page.locator('#hbm-preset-12').click();assert.equal(await page.locator('#hbm-die_thickness_um').inputValue(),'34');assert.equal(await page.locator('#hbm-gap_um').inputValue(),'8');assert.equal(await page.locator('#hbm-total-thickness').innerText(),'604 µm');
  const composed=await apply();assert.equal(composed.response.status(),200);await sectionReady();assert.equal(composed.data.twin.hbm_assemblies[0].die_count,12);
  assert.match(await page.locator('#hbm-edit-status').innerText(),/Stack applied/);
  await page.locator('#hbm-yz').click();await page.waitForFunction(()=>document.querySelector('#hbm-section').dataset.axis==='yz' && document.querySelector('#hbm-section-loading').hidden);
  await page.screenshot({path:path.join(output,'hbm-layer-editor.png'),fullPage:true});
  await close();assert.match(await page.locator('#acquisition-status').innerText(),/Settings changed/);
  const stale=await download('#export-results','previous-acquisition.json');assert.equal(stale.twin.hbm_assemblies[0].die_count,8);assert.equal(stale.export_metadata.settings_changed_since_acquisition,true);
  const edited=await download('#export-twin','twelve-high.json');assert.equal(edited.hbm_assemblies[0].die_count,12);
  await open();await page.locator('#hbm-die_thickness_um').fill('200');const rejected=await apply();assert.equal(rejected.response.status(),422);assert.match(await page.locator('#hbm-edit-status').innerText(),/Changes rejected; current twin retained/);await close();assert.deepEqual(await download('#export-twin','after-rejected.json'),edited);

  await open();await page.locator('#hbm-site').selectOption('hbm-6');await sectionReady();assert.equal(await page.locator('#hbm-functional-state').inputValue(),'unknown');
  await page.locator('#hbm-functional-state').selectOption('disabled');const disabled=await apply();assert.equal(disabled.response.status(),200);assert.deepEqual(disabled.data.twin.objects,edited.objects,'Electrical state must not change physical geometry.');assert.equal(disabled.data.twin.hbm_assemblies[5].functional_state,'disabled');await sectionReady();
  await page.locator('#hbm-scan-selected').click();assert(!(await page.locator('#hbm-dialog').isVisible()));assert.equal(await page.locator('#roi-site').inputValue(),'hbm-6');assert(await page.locator('#angle').isDisabled());assert.match(await page.locator('#roi-summary').innerText(),/full depth/);assert.equal(await page.locator('#depth-samples').inputValue(),'1024','Stack ROI chooses sufficient depth sampling when the prior value was automatic.');
  const oldFullPlot=await page.locator('#sam-map').evaluate(canvas=>canvas._plot),beforeStaleProbe=probeRequests.length;await page.locator('#sam-map').click({position:{x:oldFullPlot.left+oldFullPlot.w*.05,y:oldFullPlot.top+oldFullPlot.h*.05}});assert.match(await page.locator('#notice p').innerText(),/Run the pending specimen or scanning changes/);assert.equal(probeRequests.length,beforeStaleProbe,'Old full-map inspection must not overwrite the pending ROI probe.');
  await page.locator('#depth-samples').selectOption('512');const run=responseFor('/api/simulate');await page.locator('#run-btn').click();const roiResponse=await run;assert.equal(roiResponse.status(),200);await complete();const roiResult=await roiResponse.json(),settings=roiResponse.request().postDataJSON().settings;
  const sixth=disabled.data.twin.hbm_assemblies[5],[x,y]=sixth.center_xy_mm,[w,h]=sixth.footprint_mm,expected=[x-w/2,y-h/2,x+w/2,y+h/2];assert.deepEqual(settings.roi_mm,expected);assert.equal(settings.depth_samples,512);assert.equal(settings.angle_deg,0);assert.deepEqual(roiResult.sam.extent_mm,[expected[0],expected[2],expected[1],expected[3]]);
  assert.equal(settings.probe_x_mm,x);assert.equal(settings.probe_y_mm,y);
  const plot=await page.locator('#sam-map').evaluate(canvas=>canvas._plot),probe=responseFor('/api/probe');await page.locator('#sam-map').click({position:{x:plot.left+plot.w*.72,y:plot.top+plot.h*.65}});const inspected=await probe;assert.equal(inspected.status(),200);const inspectedSettings=inspected.request().postDataJSON().settings;assert(Math.abs(inspectedSettings.probe_x_mm-(expected[0]+w*.72))<.1);assert(Math.abs(inspectedSettings.probe_y_mm-(expected[1]+h*.65))<.1);await page.waitForFunction(()=>document.querySelector('#probe-state').textContent.startsWith('Waveform'));
  const keyboard=responseFor('/api/probe');await page.locator('#sam-map').press('ArrowRight');const moved=await keyboard;assert.equal(moved.status(),200);assert(Math.abs(moved.request().postDataJSON().settings.probe_x_mm-inspectedSettings.probe_x_mm-w/settings.resolution)<.00001);await page.waitForFunction(()=>document.querySelector('#probe-state').textContent.startsWith('Waveform'));
  const roiExport=await download('#export-results','roi-acquisition.json');assert.deepEqual(roiExport.settings.roi_mm,expected);assert.equal(roiExport.twin.hbm_assemblies[5].functional_state,'disabled');assert.equal(roiExport.export_metadata.settings_changed_since_acquisition,false);await page.screenshot({path:path.join(output,'hbm-roi-acquisition.png'),fullPage:true});
  await page.locator('#roi-site').selectOption('hbm-1');await page.locator('#roi-stack').click();assert.equal(await page.locator('#depth-samples').inputValue(),'512','ROI changes preserve explicit depth sampling.');const beforeOtherROI=probeRequests.length;await page.locator('#sam-map').press('ArrowLeft');assert.match(await page.locator('#notice p').innerText(),/Run the pending specimen or scanning changes/);assert.equal(probeRequests.length,beforeOtherROI);const otherRun=responseFor('/api/simulate');await page.locator('#run-btn').click();const otherResponse=await otherRun;assert.equal(otherResponse.status(),200);await complete();assert.equal(otherResponse.request().postDataJSON().settings.probe_x_mm,disabled.data.twin.hbm_assemblies[0].center_xy_mm[0]);assert.equal(otherResponse.request().postDataJSON().settings.probe_y_mm,disabled.data.twin.hbm_assemblies[0].center_xy_mm[1]);
  await page.locator('#roi-full').click();assert(!(await page.locator('#angle').isDisabled()));await page.locator('#depth-samples').selectOption('');const full=responseFor('/api/simulate');await page.locator('#run-btn').click();const fullResponse=await full;assert.equal(fullResponse.status(),200);await complete();assert(!Object.hasOwn(fullResponse.request().postDataJSON().settings,'roi_mm'));assert(!Object.hasOwn(fullResponse.request().postDataJSON().settings,'depth_samples'));assert.deepEqual((await fullResponse.json()).sam.extent_mm,[0,60,0,60]);

  // A closed editor must never apply an in-flight response to the current twin.
  let release,arrived;const gate=new Promise(resolve=>release=resolve),intercepted=new Promise(resolve=>arrived=resolve);
  const delayed=async route=>{const response=await route.fetch();arrived();await gate;try{await route.fulfill({response});}catch{/* The browser may already have cancelled this request. */}};
  await page.route('**/api/hbm/compose',delayed);const beforeCancelled=await download('#export-twin','before-cancelled.json');await open();await page.locator('#hbm-functional-state').selectOption((await page.locator('#hbm-functional-state').inputValue())==='enabled'?'disabled':'enabled');await page.locator('#hbm-apply').click();await intercepted;await close();release();await page.unroute('**/api/hbm/compose',delayed);assert.deepEqual(await download('#export-twin','after-cancelled.json'),beforeCancelled);

  const fallback=await context.newPage();fallback.on('pageerror',error=>errors.push(error.message));await fallback.route('**/api/reference-image',route=>route.fulfill({status:404,contentType:'application/json',body:'{"detail":"No local image"}'}));await fallback.goto(`${baseURL}/?specimen=nvidia-h100-sxm`,{waitUntil:'networkidle'});await fallback.locator('#acquisition-status').filter({hasText:'Acquisition complete'}).waitFor();await fallback.locator('#hbm-editor-btn').click();await fallback.locator('#hbm-reference').evaluate(element=>element.open=true);await fallback.locator('#hbm-reference-status').filter({hasText:'not installed'}).waitFor();assert(!(await fallback.locator('#hbm-reference-image').isVisible()));assert.equal(await fallback.locator('#hbm-reference-image').getAttribute('src'),null);await fallback.close();
  const referenceResponse=await context.request.get(`${baseURL}/api/reference-image`),referenceChecks=[];
  if(referenceResponse.ok()) {
    assert.equal(referenceResponse.headers()['x-reference-sha256'],original.image_reference.sha256);
    const referencePage=await context.newPage();referencePage.on('pageerror',error=>errors.push(error.message));
    let patch={pixel_size_um:6.2};
    await referencePage.route('**/api/examples',async route=>{const response=await route.fetch(),examples=await response.json(),twin=examples.find(item=>item.id==='nvidia-h100-sxm').twin;Object.assign(twin.image_reference,patch);await route.fulfill({response,json:examples});});
    const loadReference=async()=>{await referencePage.goto(`${baseURL}/?specimen=nvidia-h100-sxm`,{waitUntil:'networkidle'});await referencePage.locator('#acquisition-status').filter({hasText:'Acquisition complete'}).waitFor();await referencePage.locator('#hbm-editor-btn').click();await referencePage.locator('#hbm-reference').evaluate(element=>element.open=true);};
    await loadReference();await referencePage.locator('#hbm-reference-image').waitFor({state:'visible'});assert.match(await referencePage.locator('#hbm-reference-scale').innerText(),/6.2 µm\/pixel/);assert.match(await referencePage.locator('#hbm-reference-scale').innerText(),/4.30 × 3.11 mm/);
    patch={width_px:694};await loadReference();await referencePage.locator('#hbm-reference-scale').filter({hasText:'Scale metadata is inconsistent'}).waitFor();
    patch={sha256:'0'.repeat(64)};await loadReference();await referencePage.locator('#hbm-reference-status').filter({hasText:'does not match'}).waitFor();assert(!(await referencePage.locator('#hbm-reference-image').isVisible()));await referencePage.close();referenceChecks.push('local reference hash identity and natural dimensions checked','image scale and FOV use imported metadata','mismatched image identity withheld');
  }
  await page.setViewportSize({width:390,height:900});await open();await page.screenshot({path:path.join(output,'hbm-editor-mobile-controls.png')});await page.locator('#hbm-section').scrollIntoViewIfNeeded();await sectionReady();await page.screenshot({path:path.join(output,'hbm-editor-mobile-section.png')});const dialogBounds=await page.locator('#hbm-dialog').boundingBox(),sectionBounds=await page.locator('#hbm-section').boundingBox();assert(dialogBounds.x>=0 && dialogBounds.x+dialogBounds.width<=390);assert(sectionBounds.width>250 && sectionBounds.x+sectionBounds.width<=390);await close();
  assert.deepEqual(errors,[]);const report={status:'passed',artifacts:output,checks:['six physical HBM sites and seven visible component labels','editable 8/12-high geometry and material YZ section','rejected geometry retains current twin','stale acquisition retains its original twin','electrical state changes preserve exact object geometry','ROI projection and SAM acquisition at global coordinates','ROI keyboard probe movement','ROI metadata and edited stack preserved in exports','old full-map and ROI-map probes cannot overwrite pending ROI settings','full-specimen and automatic depth settings restored','closing editor discards in-flight edits','local reference absence handled without broken image',...referenceChecks,'390px editor controls and material section fit viewport','no uncaught browser errors']};await writeFile(path.join(output,'verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
} finally {await context.close();await browser.close();}
