import './depth.css';

const el=id=>document.getElementById(`depth-${id}`);
const fmt=value=>{const n=Number(value);return (Math.abs(n)<.00005?0:n).toLocaleString(undefined,{maximumFractionDigits:4});};
const signal=value=>{const n=Number(value);return n!==0&&(Math.abs(n)<.001||Math.abs(n)>=10000)?n.toExponential(3):fmt(n);};
const bytes=value=>value>=1073741824?`${(value/1073741824).toFixed(2)} GiB`:value>=1048576?`${(value/1048576).toFixed(1)} MiB`:`${(value/1024).toFixed(1)} KiB`;
const field=(id,label,value,min,max,step='any')=>`<label class="depth-number" for="depth-${id}">${label}<input id="depth-${id}" type="number" value="${value}" min="${min}" max="${max}" step="${step}" required></label>`;
const completed=item=>item.complete===true||item.state==='completed';
const active=status=>['queued','running','cancel_requested','cancelling','pending','resuming'].includes(status);
const kind='sam_depth_volume';
const axes={xy:['x','y'],xz:['x','z'],yz:['y','z']};
const evidenceLabel={user_assumed:'User-assumed model',user_calibrated:'User-declared calibration',synthetic_truth:'User-declared synthetic truth'};

export class DepthWorkspace {
  constructor({request}) {
    this.request=request;this.jobs=[];this.datasets=[];this.sources=[];this.cursor={x_index:0,y_index:0,z_index:0};this.product='rf';this.window=[-.1,.1];
    document.body.insertAdjacentHTML('beforeend',`
      <dialog id="depth-dialog" aria-labelledby="depth-title" aria-describedby="depth-intro">
        <header class="depth-header"><div><h2 id="depth-title">SAM depth mapping</h2><p id="depth-intro">Map saved acoustic recording time to depth with an explicit velocity model.</p></div><button id="depth-close" class="quiet" aria-label="Close SAM depth mapping">✕</button></header>
        <div class="depth-layout">
          <aside class="depth-acquisition" aria-label="Depth model and saved acoustic volumes">
            <details id="depth-new-panel" open><summary>New depth mapping</summary><form id="depth-form">
              <label class="depth-source-label" for="depth-source">Saved acoustic source<select id="depth-source"><option value="">Loading completed acoustic recordings…</option></select></label><p id="depth-source-detail" class="depth-hint">Uses the saved acoustic source independently of the current preview.</p>
              <fieldset><legend>Output depth grid</legend><div class="depth-fields">${field('nz','Z samples',128,16,1024,1)}${field('z_min_mm','Z minimum (mm)',0,0,6)}${field('z_max_mm','Z maximum (mm)',1,0,6)}</div><p class="depth-hint">Source X/Y positions stay unchanged, including any acquisition ROI. Finer Z sampling does not create additional axial resolution.</p></fieldset>
              <fieldset><legend>Surface time reference</legend><label class="depth-source-label" for="depth-surface_reference">Reference<select id="depth-surface_reference"><option value="source_water_delay">Saved water standoff delay</option><option value="explicit">Explicit surface time</option></select></label>${field('surface_time_us','Surface time (µs)',0,0,1000)}<p id="depth-reference-note" class="depth-hint">The surface time uses the original recording axis, not an offset from the first saved sample.</p></fieldset>
              <fieldset><legend>Velocity through the specimen</legend><label class="depth-source-label" for="depth-velocity_model">Model<select id="depth-velocity_model"><option value="homogeneous">Homogeneous velocity</option><option value="layered">Layered velocities</option></select></label><div id="depth-homogeneous">${field('sound_speed_m_s','Sound speed (m/s)',5000,.001,1000000)}</div>
                <div id="depth-layered" hidden><div class="depth-layer-heading"><span>End depth (mm)</span><span>Speed (m/s)</span><span></span></div><div id="depth-layers"></div><button id="depth-add-layer" class="small" type="button">Add layer</button><p class="depth-hint">The first layer starts at Z = 0. Each following layer starts at the previous endpoint. Depths beyond the last layer are masked.</p></div>
                <p class="depth-model-explanation">Each layer adds a two-way travel time. One velocity model applies to every X/Y position; velocities are not inferred from material labels.</p>
              </fieldset>
              <fieldset><legend>Model evidence</legend><label class="depth-source-label" for="depth-model_evidence">Basis for these velocities<select id="depth-model_evidence"><option value="user_assumed">User-assumed model</option><option value="user_calibrated">User-declared calibration</option><option value="synthetic_truth">User-declared synthetic truth</option></select></label><label class="depth-source-label" for="depth-model_note">Model note<textarea id="depth-model_note" rows="3" maxlength="4000" required>Illustrative velocity model; no specimen calibration.</textarea></label><p id="depth-evidence-note" class="depth-hint">Assumed velocities make the depth coordinate conditional on this model.</p></fieldset>
              <div id="depth-estimate" class="depth-estimate" aria-live="polite">Select a completed acoustic source.</div><details id="depth-warnings" hidden><summary>Mapping notes</summary><ul></ul></details><button id="depth-estimate-btn" class="small" type="button">Estimate depth mapping</button><button id="depth-start" class="primary" type="submit" disabled>Start depth mapping</button>
            </form></details>
            <section class="depth-jobs"><h3>Depth mapping jobs</h3><div id="depth-jobs-list"></div></section>
            <section class="depth-saved"><div class="depth-list-heading"><h3>Saved SAM depth volumes</h3><button id="depth-refresh-list" class="quiet" aria-label="Refresh saved SAM depth volumes">↻</button></div><div id="depth-datasets"></div></section>
          </aside>
          <main class="depth-inspector">
            <div id="depth-message" class="depth-message" role="status" aria-live="polite">Choose a saved acoustic recording and specify how travel time maps to depth.</div>
            <div id="depth-empty" class="depth-empty"><svg viewBox="0 0 180 125" fill="none" aria-hidden="true"><path d="M16 26h28l8-14 10 33 12-21h37M16 54h105M16 77h105M16 100h105m25-80v78m-7-9 7 10 7-10"/></svg><h3>A depth coordinate with a stated acoustic model</h3><p>Inspect signed RF and envelope values in linked XY, XZ and YZ sections. The saved recording remains the source; the chosen surface reference and sound speeds determine the derived depths.</p><p class="depth-hint">This is time-to-depth mapping, not full-wave inversion. Refraction, lateral propagation and echo identity are not recovered.</p></div>
            <div id="depth-viewer" hidden>
              <div class="depth-dataset-heading"><div><h3 id="depth-dataset-name"></h3><p id="depth-dataset-detail"></p></div><a id="depth-export" class="depth-download" href="#" download>Download Zarr archive</a></div>
              <div id="depth-saved-model" class="depth-saved-model"></div>
              <div class="depth-controls">${['x','y','z'].map(axis=>`<label for="depth-${axis}">${axis.toUpperCase()} position <output id="depth-${axis}-value"></output><input id="depth-${axis}" type="range" min="0" max="0" step="1" value="0"></label>`).join('')}<label for="depth-product">Saved signal<select id="depth-product"><option value="rf">Signed RF</option><option value="envelope">Envelope</option></select></label><label for="depth-window-min">Display minimum<input id="depth-window-min" type="number" step="any" value="-.1"></label><label for="depth-window-max">Display maximum<input id="depth-window-max" type="number" step="any" value=".1"></label></div>
              <p id="depth-view-note" class="depth-view-note">Reading saved spatial slices.</p><details id="depth-saved-notes" class="depth-saved-notes" hidden><summary>Saved mapping notes</summary><ul></ul></details>
              <div class="depth-slice-grid">${Object.keys(axes).map(plane=>`<section class="depth-plot depth-${plane}"><div><h4>${plane.toUpperCase()} section</h4><span id="depth-${plane}-caption"></span></div><canvas id="depth-${plane}" tabindex="0" role="img" aria-label="${plane.toUpperCase()} acoustic section; click or use arrow keys to move the linked cursor"></canvas></section>`).join('')}</div>
              <div class="depth-cursor"><strong id="depth-cursor-position"></strong><span id="depth-cursor-time"></span><span id="depth-cursor-signal"></span><span id="depth-cursor-valid"></span></div>
              <div class="depth-legend"><output id="depth-window-low"></output><i id="depth-colorbar"></i><output id="depth-window-high"></output><span>Relative amplitude</span><span class="depth-mask-key"><b></b>Outside recording or velocity-model support</span></div>
              <p class="depth-hint">Gray values are masked placeholders, not measured zero-amplitude echoes. Axes are scaled independently for inspection; use the millimeter labels for dimensions. Display limits clip colors only; cursor values and exports retain the saved amplitudes. The source signal is synthetic, and model evidence is a user declaration.</p><p id="depth-provenance" class="depth-hint"></p>
            </div>
          </main>
        </div>
      </dialog>`);
    el('close').addEventListener('click',()=>el('dialog').close());
    el('dialog').addEventListener('close',()=>{for(const key of ['pollTimer','estimateTimer','viewTimer'])clearTimeout(this[key]);for(const key of ['catalogController','sourceController','selectionController','estimateController','viewController'])this[key]?.abort();});
    el('refresh-list').addEventListener('click',()=>this.catalog());
    el('source').addEventListener('change',()=>this.selectSource(el('source').value));
    el('form').addEventListener('input',event=>{if(event.target!==el('source'))this.changed();});
    el('estimate-btn').addEventListener('click',()=>this.estimate());
    el('form').addEventListener('submit',event=>{event.preventDefault();this.start();});
    el('add-layer').addEventListener('click',()=>{const layers=this.layers(),last=layers.at(-1)?.end_depth_mm||0,max=this.source?.request?.twin?.size_mm?.[2]||6;this.addLayer(Math.min(max,last+.25),5000);this.changed();});
    for(const axis of ['x','y','z'])el(axis).addEventListener('input',event=>{this.cursor[`${axis}_index`]=Number(event.target.value);this.viewSoon();});
    el('product').addEventListener('change',()=>{this.product=el('product').value;this.window=this.product==='rf'?[-.1,.1]:[0,.1];el('window-min').value=this.window[0];el('window-max').value=this.window[1];this.viewSoon();});
    for(const id of ['window-min','window-max'])el(id).addEventListener('input',()=>{const min=Number(el('window-min').value),max=Number(el('window-max').value);if(!Number.isFinite(min)||!Number.isFinite(max)||min>=max){this.message('Display maximum must exceed its minimum.',true);return;}this.window=[min,max];this.message('Display limits applied to saved signal values.');this.draw();});
    for(const plane of Object.keys(axes)){el(plane).addEventListener('click',event=>this.pick(plane,event));el(plane).addEventListener('keydown',event=>this.move(plane,event));}
    new ResizeObserver(()=>this.draw()).observe(document.querySelector('.depth-inspector'));
  }
  open(){if(el('dialog').open)return;el('dialog').showModal();this.catalog();if(this.source)this.changed();else if(el('source').value)this.selectSource(el('source').value);if(this.manifest)this.loadView();requestAnimationFrame(()=>this.draw());}
  message(text,error=false){el('message').textContent=text;el('message').classList.toggle('error',error);}
  layers(){return [...el('layers').querySelectorAll('.depth-layer')].map(row=>({end_depth_mm:Number(row.querySelector('[data-field="end"]').value),sound_speed_m_s:Number(row.querySelector('[data-field="speed"]').value)}));}
  addLayer(end,speed){const row=document.createElement('div');row.className='depth-layer';row.innerHTML='<input type="number" data-field="end" aria-label="Layer end depth (mm)" min="0.000001" step="any" required><input type="number" data-field="speed" aria-label="Layer sound speed (m/s)" min="0.001" max="1000000" step="any" required><button type="button" class="quiet" aria-label="Remove velocity layer">×</button>';row.querySelector('[data-field="end"]').value=end;row.querySelector('[data-field="end"]').max=this.source?.request?.twin?.size_mm?.[2]||6;row.querySelector('[data-field="speed"]').value=speed;row.querySelector('button').addEventListener('click',()=>{row.remove();this.changed();});el('layers').append(row);}
  payload(){const mapping={nz:Number(el('nz').value),z_min_mm:Number(el('z_min_mm').value),z_max_mm:Number(el('z_max_mm').value),surface_reference:el('surface_reference').value,velocity_model:el('velocity_model').value,sound_speed_m_s:Number(el('sound_speed_m_s').value),layers:el('velocity_model').value==='layered'?this.layers():[],model_evidence:el('model_evidence').value,model_note:el('model_note').value};if(mapping.surface_reference==='explicit')mapping.surface_time_us=Number(el('surface_time_us').value);return {kind,source_dataset_id:this.source?.dataset_id||this.source?.id,mapping};}
  changed(){this.estimateKey=null;el('start').disabled=true;this.estimateController?.abort();clearTimeout(this.estimateTimer);const layered=el('velocity_model').value==='layered';el('layered').hidden=!layered;el('homogeneous').hidden=layered;el('sound_speed_m_s').disabled=layered;for(const input of el('layers').querySelectorAll('input'))input.disabled=!layered;el('surface_time_us').disabled=el('surface_reference').value!=='explicit';el('reference-note').textContent=el('surface_reference').value==='explicit'?'Surface time is on the original recording axis, not relative to the first saved sample.':'Surface time is resolved from the frozen source water standoff. The original recording axis is preserved.';el('evidence-note').textContent=el('model_evidence').value==='user_assumed'?'Assumed velocities make the depth coordinate conditional on this model.':'This label records your stated basis. The software does not verify calibration or agreement with synthetic ground truth.';el('estimate').textContent=this.source?'Settings changed. Estimating depth mapping…':'Select a completed acoustic source.';if(this.source)this.estimateTimer=setTimeout(()=>this.estimate(),350);}
  async selectSource(id){this.sourceController?.abort();this.estimateController?.abort();this.source=null;this.changed();if(!id)return;const controller=this.sourceController=new AbortController();el('source-detail').textContent='Reading frozen acoustic source…';try{const source=await this.request(`/api/v2/datasets/${encodeURIComponent(id)}`,null,controller.signal);if(controller!==this.sourceController||!el('dialog').open)return;const size=source.request?.twin?.size_mm;if(!size)throw new Error('The acoustic source is missing frozen specimen bounds.');this.source=source;el('z_min_mm').value=0;el('z_max_mm').value=size[2];for(const key of ['z_min_mm','z_max_mm'])el(key).max=size[2];el('layers').replaceChildren();this.addLayer(size[2],5000);const time=source.time_range_us||[];el('source-detail').textContent=`${source.name}. Saved X/Y raster ${source.shape[1]} × ${source.shape[0]}, ${source.shape[2]} time samples${time.length?` from ${fmt(time[0])} to ${fmt(time[1])} µs`:''}. Specimen depth ${fmt(size[2])} mm. Source ${id}. The current twin and ROI are not used.`;this.changed();}catch(error){if(error.name!=='AbortError'){this.source=null;el('source-detail').textContent=error.message;this.message(error.message,true);}}}
  async estimate(){clearTimeout(this.estimateTimer);if(!this.source||!el('dialog').open)return;if(!el('form').checkValidity()){el('estimate').textContent='Correct the mapping fields before estimating.';return;}const body=this.payload(),key=JSON.stringify(body),m=body.mapping;if(m.z_max_mm<=m.z_min_mm){el('estimate').textContent='Z maximum must exceed Z minimum.';return;}if(m.velocity_model==='layered'&&(!m.layers.length||m.layers.some((layer,index)=>layer.end_depth_mm<=(m.layers[index-1]?.end_depth_mm||0)))){el('estimate').textContent='Add at least one layer, with strictly increasing end depths from Z = 0.';return;}this.estimateController?.abort();const controller=this.estimateController=new AbortController();el('start').disabled=true;try{const result=await this.request('/api/v2/estimate',body,controller.signal);if(controller!==this.estimateController||key!==JSON.stringify(this.payload()))return;this.estimateKey=key;if(m.surface_reference==='source_water_delay'&&Number.isFinite(result.surface_time_us))el('surface_time_us').value=result.surface_time_us;el('estimate').textContent=`${result.shape.join(' × ')} samples (Z, Y, X). RF, envelope and validity: ${bytes(result.total_bytes)}. Estimated peak memory: ${bytes(result.estimated_peak_bytes)}.${result.estimated_temporary_bytes!==undefined?` Temporary disk: ${bytes(result.estimated_temporary_bytes)}.`:''}${result.depth_pitch_mm!==undefined?` Z pitch: ${fmt(result.depth_pitch_mm*1000)} µm.`:''}${result.valid_depth_samples!==undefined?` ${result.valid_depth_samples}/${result.shape[0]} depth samples within recording and model support.`:''}${result.voxel_pitch_mm?` Pitch X/Y/Z: ${result.voxel_pitch_mm.map(value=>fmt(value*1000)).join(' / ')} µm.`:''}${Number.isFinite(result.surface_time_us)?` Surface time: ${fmt(result.surface_time_us)} µs.`:''}`;this.notes('warnings',result.warnings||[],'Mapping notes');el('start').disabled=Boolean(this.starting);}catch(error){if(error.name!=='AbortError'&&controller===this.estimateController){this.estimateKey=null;el('estimate').textContent=error.message;}}}
  notes(id,warnings,label){el(id).hidden=!warnings.length;el(id).querySelector('summary').textContent=`${label} (${warnings.length})`;el(id).querySelector('ul').replaceChildren();for(const warning of warnings){const li=document.createElement('li');li.textContent=warning;el(id).querySelector('ul').append(li);}}
  async start(){if(this.starting||!this.source||!el('form').reportValidity())return;const body=this.payload();if(this.estimateKey!==JSON.stringify(body)){await this.estimate();if(this.estimateKey!==JSON.stringify(body))return;}this.starting=true;el('start').disabled=true;el('start').textContent='Submitting…';try{const job=await this.request('/api/v2/jobs',body);this.pendingId=job.dataset_id;el('new-panel').open=false;this.message('Depth mapping submitted. The saved recording and declared velocity model are frozen with this dataset.');await this.catalog();}catch(error){this.message(error.message,true);}finally{this.starting=false;el('start').textContent='Start depth mapping';el('start').disabled=!this.estimateKey;}}
  async catalog(){clearTimeout(this.pollTimer);this.catalogController?.abort();const controller=this.catalogController=new AbortController();try{const [jobs,data]=await Promise.all([this.request('/api/v2/jobs',null,controller.signal),this.request('/api/v2/datasets',null,controller.signal)]);if(controller!==this.catalogController)return;this.jobs=jobs.jobs.filter(item=>item.kind===kind);this.datasets=data.datasets.filter(item=>item.kind===kind);this.sources=data.datasets.filter(item=>item.kind==='sam_rf_volume'&&completed(item));this.renderCatalog();const pending=this.datasets.find(item=>(item.dataset_id||item.id)===this.pendingId&&completed(item));if(pending){this.pendingId=null;await this.select(pending.dataset_id||pending.id);}else if(!this.manifest&&!this.selecting){let saved;try{saved=localStorage.getItem('virtual-microscopy-last-depth');}catch{}const found=this.datasets.find(item=>completed(item)&&(item.dataset_id||item.id)===saved)||this.datasets.find(completed);if(found)await this.select(found.dataset_id||found.id);}}catch(error){if(error.name!=='AbortError')this.message(`SAM depth catalog unavailable: ${error.message}`,true);}finally{if(controller===this.catalogController&&el('dialog').open)this.pollTimer=setTimeout(()=>this.catalog(),this.jobs.some(job=>active(job.status))?1200:6000);}}
  renderCatalog(){const ordered=list=>[...list].sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||'')));const sourceSignature=JSON.stringify(this.sources.map(source=>[source.dataset_id||source.id,source.name,source.shape]));if(sourceSignature!==this.sourceSignature){this.sourceSignature=sourceSignature;const selected=el('source').value;el('source').replaceChildren();if(!this.sources.length){const option=document.createElement('option');option.value='';option.textContent='Acquire an acoustic RF volume first';el('source').append(option);}for(const source of ordered(this.sources)){const option=document.createElement('option'),id=source.dataset_id||source.id;option.value=id;option.textContent=`${source.name} — ${source.shape.join(' × ')} — ${id.slice(0,8)}`;el('source').append(option);}el('source').value=this.sources.some(source=>(source.dataset_id||source.id)===selected)?selected:el('source').options[0]?.value||'';if(!this.source&&el('source').value)this.selectSource(el('source').value);}
    const signature=JSON.stringify([this.jobs,this.datasets,this.manifest?.dataset_id]);if(signature===this.catalogSignature)return;this.catalogSignature=signature;el('jobs-list').replaceChildren();el('datasets').replaceChildren();if(!this.jobs.length)el('jobs-list').textContent='No depth mapping jobs yet.';
    for(const job of ordered(this.jobs).slice(0,8)){const row=document.createElement('div');row.className='depth-job';row.dataset.jobId=job.id;const title=document.createElement('strong'),done=job.completed_units??0,total=job.total_units??1;title.textContent=`${job.status.replaceAll('_',' ')} · ${done}/${total} slices`;const progress=document.createElement('progress');progress.max=total;progress.value=done;progress.setAttribute('aria-label',`Depth mapping ${job.id} progress`);row.append(title,progress);if(job.error){const error=document.createElement('p');error.textContent=job.error;row.append(error);}const action=active(job.status)?'cancel':['cancelled','interrupted','failed'].includes(job.status)?'resume':null;if(action){const button=document.createElement('button');button.className='small';button.dataset.action=action;button.textContent=action==='cancel'?'Cancel depth mapping':'Resume depth mapping';button.addEventListener('click',async()=>{button.disabled=true;try{const result=await this.request(`/api/v2/jobs/${encodeURIComponent(job.id)}/${action}`,{});if(action==='resume')this.pendingId=result.dataset_id;this.message(action==='cancel'?'Cancellation requested. Completed depth slices remain saved.':'Resuming the saved depth mapping.');await this.catalog();}catch(error){button.disabled=false;this.message(error.message,true);}});row.append(button);}el('jobs-list').append(row);}
    if(!this.datasets.length)el('datasets').textContent='No saved SAM depth volumes.';for(const data of ordered(this.datasets)){const id=data.dataset_id||data.id,button=document.createElement('button');button.className='depth-dataset';button.dataset.datasetId=id;button.disabled=!completed(data);button.setAttribute('aria-pressed',String(id===(this.manifest?.dataset_id||this.manifest?.id)));for(const [tag,text] of [['strong',data.name],['span',`${data.shape.join(' × ')} · ${data.state}`],['span',`${new Date(data.created_at).toLocaleString()} · ${id.slice(0,8)}`]]){const child=document.createElement(tag);child.textContent=text;button.append(child);}button.addEventListener('click',()=>this.select(id));el('datasets').append(button);}}
  async select(id){this.selectionController?.abort();this.viewController?.abort();const controller=this.selectionController=new AbortController();this.selecting=true;el('view-note').textContent='Opening saved SAM depth volume…';for(const key of ['x','y','z','product'])el(key).disabled=true;try{const data=await this.request(`/api/v2/datasets/${encodeURIComponent(id)}`,null,controller.signal);if(controller!==this.selectionController||!el('dialog').open)return;if(data.kind!==kind||!completed(data))throw new Error('Open a completed SAM depth volume. Resume incomplete jobs first.');this.manifest=data;this.view=null;el('saved-notes').hidden=true;for(const key of ['cursor-position','cursor-time','cursor-signal','cursor-valid'])el(key).textContent='';for(const plane of Object.keys(axes)){el(`${plane}-caption`).textContent='';const canvas=el(plane);canvas.getContext('2d').clearRect(0,0,canvas.width,canvas.height);canvas._depthPlot=null;delete canvas.dataset.rows;}for(const [axis,index] of [['x',2],['y',1],['z',0]]){this.cursor[`${axis}_index`]=Math.floor(data.shape[index]/2);el(axis).max=data.shape[index]-1;}el('dataset-name').textContent=data.name;el('dataset-detail').textContent=`${data.shape.join(' × ')} samples · Z, Y, X · source X/Y positions preserved`;el('export').href=`/api/v2/datasets/${encodeURIComponent(id)}/export`;el('viewer').hidden=false;el('empty').hidden=true;const m=data.mapping||data.request?.mapping||{};el('saved-model').textContent=`${evidenceLabel[m.model_evidence]||'Declared velocity model'}. ${m.velocity_model==='layered'?`Layered model: ${m.layers.map(layer=>`${fmt(layer.end_depth_mm)} mm endpoint at ${fmt(layer.sound_speed_m_s)} m/s`).join('; ')}`:`Homogeneous sound speed ${fmt(m.sound_speed_m_s)} m/s`}. ${m.model_note||''}`;el('provenance').textContent=`Depth dataset ${id}. Source acoustic dataset ${data.source_dataset_id||data.request?.source_dataset_id}. Surface reference: ${m.surface_reference==='explicit'?'explicit original-axis time':'frozen source water delay'}. This volume maps synthetic RF recording time through the declared model; it is not full-wave inversion or experimental validation.`;try{localStorage.setItem('virtual-microscopy-last-depth',id);}catch{}this.renderCatalog();this.selecting=false;await this.loadView();}catch(error){if(error.name!=='AbortError')this.message(error.message,true);}finally{if(controller===this.selectionController){this.selecting=false;for(const key of ['x','y','z','product'])el(key).disabled=false;}}}
  viewSoon(){if(this.selecting)return;this.viewController?.abort();clearTimeout(this.viewTimer);this.viewTimer=setTimeout(()=>this.loadView(),90);}
  async loadView(){if(!this.manifest||!el('dialog').open)return;this.viewController?.abort();const controller=this.viewController=new AbortController(),id=this.manifest.dataset_id||this.manifest.id;el('view-note').textContent='Reading saved spatial slices…';try{const view=await this.request(`/api/v2/datasets/${encodeURIComponent(id)}/depth-view?${new URLSearchParams({...this.cursor,product:this.product})}`,null,controller.signal);if(controller!==this.viewController||id!==(this.manifest?.dataset_id||this.manifest?.id))return;this.view=view;this.viewProduct=view.product||view.metadata?.product||this.product;for(const axis of ['x','y','z']){this.cursor[`${axis}_index`]=view.cursor[`${axis}_index`];el(axis).value=this.cursor[`${axis}_index`];el(`${axis}-value`).textContent=`${fmt(view.cursor[`${axis}_mm`])} mm`;}for(const [plane,normal] of [['xy','z'],['xz','y'],['yz','x']])el(`${plane}-caption`).textContent=`${normal.toUpperCase()} = ${fmt(view.cursor[`${normal}_mm`])} mm`;el('view-note').textContent='Reading saved data only. Moving the linked cursor, switching signals or changing display limits does not remap the recording.';el('cursor-position').textContent=`X ${fmt(view.cursor.x_mm)} / Y ${fmt(view.cursor.y_mm)} / Z ${fmt(view.cursor.z_mm)} mm`;el('cursor-time').textContent=view.cursor.sample_time_us===null?'Travel time unavailable beyond the velocity model':`Original recording time ${fmt(view.cursor.sample_time_us)} µs`;el('cursor-signal').textContent=view.cursor.valid?`RF ${signal(view.cursor.rf)} · envelope ${signal(view.cursor.envelope)}`:'Signal masked; stored zeros are placeholders';el('cursor-valid').textContent=view.cursor.valid?'Supported by saved recording':view.cursor.model_valid===false?'Outside velocity-model support':'Outside recorded time support';this.notes('saved-notes',view.metadata?.warnings||[],'Saved mapping notes');this.message('Saved SAM depth volume ready. Click a section or use the arrow keys to inspect the linked physical cursor.');this.draw();}catch(error){if(error.name!=='AbortError'&&controller===this.viewController){this.message(`Depth view unavailable: ${error.message}`,true);el('view-note').textContent='Requested view was not applied; the previous saved slices remain visible.';}}}
  draw(){if(!this.view||!el('dialog').open)return;for(const [plane,coordinates] of Object.entries(axes))drawSlice(el(plane),this.view[plane],coordinates,this.view.cursor,this.window,this.viewProduct);el('window-low').textContent=signal(this.window[0]);el('window-high').textContent=signal(this.window[1]);const from=`rgb(${rgbFor(this.window[0],this.window,this.viewProduct).join(',')})`,to=`rgb(${rgbFor(this.window[1],this.window,this.viewProduct).join(',')})`,zeroPercent=-this.window[0]/(this.window[1]-this.window[0])*100;el('colorbar').style.background=this.viewProduct==='rf'&&zeroPercent>0&&zeroPercent<100?`linear-gradient(90deg,${from},#f4f7fb ${zeroPercent}%,${to})`:`linear-gradient(90deg,${from},${to})`;}
  pick(plane,event){const canvas=el(plane),plot=canvas._depthPlot;if(!plot||!this.view||this.selecting)return;const rect=canvas.getBoundingClientRect(),fx=(event.clientX-rect.left-plot.left)/plot.width,fy=(event.clientY-rect.top-plot.top)/plot.height;if(fx<0||fx>1||fy<0||fy>1)return;const [horizontal,vertical]=axes[plane];this.cursor[`${horizontal}_index`]=Math.min(plot.cols-1,Math.floor(fx*plot.cols));this.cursor[`${vertical}_index`]=Math.min(plot.rows-1,Math.floor(fy*plot.rows));this.viewSoon();}
  move(plane,event){if(!this.view||this.selecting||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();const horizontal=['ArrowLeft','ArrowRight'].includes(event.key),axis=axes[plane][horizontal?0:1],sign=['ArrowLeft','ArrowUp'].includes(event.key)?-1:1,max=this.manifest.shape[{x:2,y:1,z:0}[axis]]-1;this.cursor[`${axis}_index`]=Math.max(0,Math.min(max,this.cursor[`${axis}_index`]+sign*(event.shiftKey?10:1)));this.viewSoon();}
}

function rgbFor(value,window,product){const f=Math.min(1,Math.max(0,(value-window[0])/(window[1]-window[0])));if(product==='envelope'){const v=Math.round(f*255);return [v,v,v];}const middle=Math.min(1,Math.max(0,-window[0]/(window[1]-window[0]))),white=[244,247,251],blue=[34,94,168],orange=[198,84,47];const from=f<=middle?blue:white,to=f<=middle?white:orange,t=f<=middle?(middle?f/middle:1):((f-middle)/(1-middle)||0);return from.map((channel,index)=>Math.round(channel+(to[index]-channel)*t));}
function drawSlice(canvas,data,axes,cursor,window,product){const width=canvas.clientWidth,height=canvas.clientHeight;if(!width||!height||!data?.image?.length)return;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.fillStyle='#fafcfd';ctx.fillRect(0,0,width,height);const rows=data.image.length,cols=data.image[0].length,off=document.createElement('canvas');off.width=cols;off.height=rows;const oc=off.getContext('2d'),pixels=oc.createImageData(cols,rows);for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const value=data.image[y][x],valid=Boolean(data.valid_mask?.[y]?.[x]),rgb=valid&&Number.isFinite(value)?rgbFor(value,window,product):[136,147,157];pixels.data.set([...rgb,255],(y*cols+x)*4);}oc.putImageData(pixels,0,0);const left=59,top=14,w=width-left-20,h=height-top-41,[a0,a1,b0,b1]=data.extent_mm;ctx.imageSmoothingEnabled=false;ctx.drawImage(off,left,top,w,h);ctx.strokeStyle='#b6c8d8';ctx.strokeRect(left,top,w,h);ctx.font='10px "Segoe UI",sans-serif';ctx.fillStyle='#55718a';for(let i=0;i<=4;i++){const f=i/4;ctx.textAlign='center';ctx.fillText(fmt(a0+(a1-a0)*f),left+w*f,top+h+17);ctx.textAlign='right';ctx.fillText(fmt(b0+(b1-b0)*f),left-7,top+h*f+3);}ctx.textAlign='center';ctx.fillText(`${axes[0].toUpperCase()} (mm)`,left+w/2,height-3);ctx.save();ctx.translate(12,top+h/2);ctx.rotate(-Math.PI/2);ctx.fillText(`${axes[1].toUpperCase()} (mm)`,0,0);ctx.restore();const x=left+(cursor[`${axes[0]}_mm`]-a0)/(a1-a0)*w,y=top+(cursor[`${axes[1]}_mm`]-b0)/(b1-b0)*h;ctx.strokeStyle='#26b9bb';ctx.setLineDash([5,3]);ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,top+h);ctx.moveTo(left,y);ctx.lineTo(left+w,y);ctx.stroke();ctx.setLineDash([]);canvas._depthPlot={left,top,width:w,height:h,rows,cols};canvas.dataset.rows=rows;canvas.dataset.columns=cols;}
