import './observations.css';
import {drawCausalMap} from './causal-volumes.js';
import {drawLayeredCurve} from './layered-plots.js';

const API='/api/v2/observations',KIND='sam_coherent_observation_volume',SOURCE='sam_causal_rf_volume';
const $=id=>document.getElementById(`ob-${id}`),idOf=item=>item?.dataset_id||item?.id;
const complete=item=>item?.complete===true||['complete','completed'].includes(item?.state||item?.status);
const active=state=>['queued','running','preparing','cancelling','cancel_requested'].includes(state);
const fmt=value=>value==null?'—':typeof value!=='number'?String(value):Math.abs(value)>0&&Math.abs(value)<.001?value.toExponential(5):value.toLocaleString(undefined,{maximumFractionDigits:7});
const bytes=value=>value==null?'—':`${(value/2**20).toFixed(2)} MiB`;
const products={rf:'Signed real pressure',imaginary:'Imaginary quadrature',envelope:'Recomputed complex magnitude'};
const bounds=[['source_propagation','Propagated source error bound'],['complex_arithmetic','Complex mixing arithmetic'],['complex_total','Total complex-pressure bound'],['magnitude_arithmetic','Magnitude arithmetic'],['magnitude_total','Total magnitude bound']];

// Keep the instrument's pale-blue paper/navy axes. The support ring and exact
// 3×3 stencil explain the operation; controls never suggest a calibrated beam.
export class ObservationWorkspace {
  constructor({request}){
    this.request=request;this.sources=[];this.jobs=[];this.datasets=[];this.cursor={x_index:0,y_index:0,time_index:0};this.product='rf';this.ceiling=.5;
    document.body.insertAdjacentHTML('beforeend',`
      <dialog id="ob-dialog" aria-labelledby="ob-title"><header class="ob-header"><div><h2 id="ob-title">Finite coherent spatial filter</h2><p>Derive a full-support interior from saved complex pressure.</p></div><button id="ob-close" class="quiet" aria-label="Close finite coherent spatial filter">✕</button></header>
        <div class="ob-layout"><aside class="ob-sidebar"><details id="ob-process-panel" open><summary>New derived observation</summary><form id="ob-form">
          <label for="ob-source">Completed independent-column source<select id="ob-source" required><option value="">Select a causal volume</option></select></label><p id="ob-source-note" class="ob-hint">The source supplies the entire excitation, recording and material response. Current specimen edits are unrelated.</p>
          <label for="ob-name">Output name (optional)<input id="ob-name" maxlength="160" placeholder="Describe this derived observation"></label><label for="ob-tolerance">Output absolute error ceiling<input id="ob-tolerance" type="number" value="1e-7" min="1e-12" max="1e-3" step="any" required></label>
          <div class="ob-stencil"><h3>Fixed coherent weights</h3><div class="ob-weight-grid" aria-label="Weights one two one, two four two, one two one, divided by sixteen">${[1,2,1,2,4,2,1,2,1].map(n=>`<span>${n}/16</span>`).join('')}</div><p class="ob-hint">Row-major 3×3 neighbors; zero added phase. Mix signed real and imaginary pressure, then recompute magnitude. Source magnitudes are not averaged.</p></div>
          <p class="ob-hint">Only positions with all nine source neighbors are retained. No reflected, wrapped or invented edge samples. No focus, gain, new carrier, time resampling or noise is applied.</p>
          <div id="ob-estimate" class="ob-evidence">Estimate complete support and resources before starting.</div><button id="ob-estimate-btn" class="small" type="button">Estimate support & resources</button><button id="ob-start" class="primary" disabled>Start derived observation</button>
        </form><details id="ob-estimate-detail" hidden><summary>Frozen estimate details</summary><pre id="ob-estimate-json"></pre></details></details>
        <section class="ob-catalog"><h3>Processing jobs</h3><div id="ob-jobs"></div></section><section class="ob-catalog"><div class="ob-list-heading"><h3>Saved observations</h3><button id="ob-refresh" class="quiet" aria-label="Refresh observations">↻</button></div><div id="ob-datasets"></div></section></aside>
        <main class="ob-inspector"><p id="ob-status" class="ob-status" role="status" aria-live="polite">Select a saved causal source. This operation mixes existing waveforms; it does not rerun propagation.</p>
          <details id="ob-support-panel" open><summary>Available source support and retained interior</summary><p id="ob-support-note" class="ob-hint">Estimate the selected source to inspect the exact retained coordinate extent.</p><div class="ob-support-grid"><section><h4>Available source field</h4><canvas id="ob-support-source" role="img" aria-label="Available source cells and one-cell support ring"></canvas><p id="ob-source-extent" class="ob-hint"></p></section><section><h4>Retained full-support centers</h4><canvas id="ob-support-interior" role="img" aria-label="Retained interior compared with source support"></canvas><p id="ob-output-extent" class="ob-hint"></p></section></div><p id="ob-support-offsets" class="ob-hint"></p></details>
          <section id="ob-empty" class="ob-empty"><h3>Preserve coherence while mixing neighboring columns.</h3><p>The fixed stencil observes the complete recorded complex waveform. This is a declared finite spatial filter, not a calibrated focused SAM beam or a claim of improved resolution.</p></section>
          <section id="ob-viewer" hidden><div class="ob-heading"><div><h3 id="ob-dataset-name"></h3><p id="ob-dataset-detail" class="ob-hint"></p></div><div class="ob-actions"><button id="ob-use-saved" class="small">Use source & ceiling as draft</button><a id="ob-export" download>Download Zarr ZIP</a></div></div>
            <p class="ob-model-note">Finite coherent spatial filter, with an inherited gamma recording. Magnitude is recomputed after complex mixing, not a Hilbert envelope of the real trace. Repeated echoes have no unique depth. Independent-column comparisons, depth mapping and recipes remain separate.</p>
            <div class="ob-cursors">${['x','y','time'].map(key=>`<label for="ob-${key}">${key==='time'?'Recorded time':key.toUpperCase()} <output id="ob-${key}-value"></output><input id="ob-${key}" type="range" min="0" max="0" value="0" step="1"></label>`).join('')}</div>
            <div class="ob-controls"><label for="ob-product">Map product<select id="ob-product">${Object.entries(products).map(([key,label])=>`<option value="${key}">${label}</option>`).join('')}</select></label><label for="ob-ceiling">Display amplitude ceiling<input id="ob-ceiling" type="number" min="1e-16" value=".5" step="any"></label><button id="ob-fit" class="small">Fit selected trace</button><label class="ob-check"><input id="ob-quadrature" type="checkbox" checked>Show quadrature</label></div>
            <form id="ob-gate-form" class="ob-controls"><label for="ob-gate-start">Gate start (µs)<input id="ob-gate-start" type="number" step="any" required></label><label for="ob-gate-end">Gate end (µs)<input id="ob-gate-end" type="number" step="any" required></label><label for="ob-gate-mode">Gate statistic<select id="ob-gate-mode"><option value="peak_envelope">Peak recomputed magnitude</option><option value="rms_rf">RMS signed real pressure</option></select></label><button id="ob-apply-gate" class="small">Apply saved-time gate</button></form>
            <p id="ob-view-note" class="ob-hint"></p><div class="ob-map-grid">${[['xy','XY at saved time'],['cscan','Gated observation'],['xt','X–time section'],['yt','Y–time section']].map(([id,title])=>`<section class="ob-plot"><header><h4>${title}</h4><span id="ob-${id}-caption"></span></header><canvas id="ob-${id}" tabindex="0" role="img" aria-label="Derived ${title}; select saved coordinate"></canvas></section>`).join('')}</div>
            <section class="ob-trace"><header><h4>Derived complex-pressure trace</h4><span>Blue: real · Purple: quadrature · Green: recomputed magnitude</span></header><canvas id="ob-ascan" tabindex="0" role="img" aria-label="Derived real, imaginary and recomputed magnitude at actual saved times"></canvas></section>
            <p id="ob-readout" class="ob-readout"></p><section class="ob-certificate"><h4>Observation numerical certificate</h4><p id="ob-bound-note" class="ob-hint"></p><div id="ob-bound-table"></div><div class="ob-bound-inspection"><label for="ob-bound-product">Spatial certificate component<select id="ob-bound-product">${bounds.map(([key,label])=>`<option value="${key}" ${key==='complex_total'?'selected':''}>${label}</option>`).join('')}</select></label><p id="ob-bound-scale" class="ob-hint"></p><canvas id="ob-bound-map" tabindex="0" role="img" aria-label="Per-output-column bound map; uniform across saved recording time"></canvas></div><p class="ob-hint">Bounds cover the declared observed complex pressure and magnitude at all retained time centers. Gate reductions, physical model suitability, geometry/material uncertainty and detectability are not newly certified. Display values are rounded; exports retain the authoritative float64 values.</p></section>
            <details id="ob-provenance"><summary>Frozen source, operator and certificate evidence</summary><pre id="ob-provenance-json"></pre></details>
          </section>
        </main></div>
      </dialog>`);
    $('close').onclick=()=>$('dialog').close();$('dialog').onclose=()=>{clearTimeout(this.pollTimer);clearTimeout(this.viewTimer);for(const name of ['catalogController','sourceController','estimateController','selectionController','viewController'])this[name]?.abort();};
    $('source').onchange=()=>this.selectSource($('source').value);$('form').oninput=()=>this.changed();$('form').onsubmit=event=>{event.preventDefault();this.start();};$('estimate-btn').onclick=()=>this.estimate();$('refresh').onclick=()=>this.refresh();$('use-saved').onclick=()=>this.useSaved();
    for(const key of ['x','y','time'])$(key).oninput=()=>{this.cursor[`${key}_index`]=Number($(key).value);this.loadViewSoon();};
    $('product').onchange=()=>{this.product=$('product').value;this.loadViewSoon();};$('quadrature').onchange=()=>this.draw();$('ceiling').oninput=()=>{const v=Number($('ceiling').value);if(v>0&&Number.isFinite(v)){this.ceiling=v;this.draw();}};$('fit').onclick=()=>{if(!this.view)return;this.ceiling=Math.max(1e-12,...this.view.ascan.envelope.map(Math.abs))*1.04;$('ceiling').value=this.ceiling;this.draw();};
    $('gate-form').onsubmit=event=>{event.preventDefault();if(!$('gate-form').reportValidity())return;this.gate={start_us:Number($('gate-start').value),end_us:Number($('gate-end').value),mode:$('gate-mode').value};this.loadViewSoon();};
    for(const id of ['xy','cscan','xt','yt','ascan','bound-map']){$(id).onclick=event=>this.pick(id,event);$(id).onkeydown=event=>this.keyboard(id,event);}
    $('bound-product').onchange=()=>this.draw();$('support-panel').ontoggle=()=>this.drawSupport();new ResizeObserver(()=>{this.draw();this.drawSupport();}).observe(document.querySelector('.ob-inspector'));
  }
  message(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
  async open(options={}){if(!$('dialog').open)$('dialog').showModal();this.openSource=options.datasetId||null;await this.refresh();if(options.datasetId){$('process-panel').open=true;await this.selectSource(options.datasetId);if(idOf(this.source)===options.datasetId)this.message('Saved independent-column source staged. Review its inherited recording and estimate the complete support.');}else if(!this.manifest){let saved;try{saved=localStorage.getItem('vm-last-observation');}catch{}const match=this.datasets.find(d=>idOf(d)===saved&&complete(d));if(match)await this.selectDataset(idOf(match));}requestAnimationFrame(()=>{this.draw();this.drawSupport();});}
  payload(){return {kind:KIND,name:$('name').value.trim(),source_dataset_id:$('source').value,operator:'binomial_3x3_coherent_v1',absolute_tolerance:Number($('tolerance').value)};}
  changed(){this.estimateController?.abort();this.estimateKey=null;$('start').disabled=true;$('estimate').textContent='Draft changed. Estimate full support and resources again.';$('estimate-detail').hidden=true;if(this.supportMode==='draft')$('support-note').textContent='Previous estimate retained for inspection; it is stale until this draft is estimated again.';}
  async selectSource(id){
    this.sourceController?.abort();this.source=null;this.changed();$('source').value=id;const controller=this.sourceController=new AbortController();if(!id){$('source-note').textContent='Select a completed independent-column causal source.';return;}$('source-note').textContent='Reading frozen source metadata…';
    try{const source=await this.request(`/api/v2/datasets/${id}`,null,controller.signal);if(controller!==this.sourceController||$('source').value!==id)return;if(source.kind!==SOURCE||!complete(source))throw new Error('Only completed independent-column causal volumes are supported; derived chains are not accepted.');this.source=source;const a=source.acquisition||source.request?.acquisition||{};$('source-note').textContent=`${source.name}. ${source.shape.join(' × ')} samples (y, x, time). Inherited ${fmt(a.center_frequency_mhz)} MHz gamma, bandwidth ${fmt(a.fractional_bandwidth)}, order ${fmt(a.gamma_order)}, ${fmt(a.sample_rate_mhz)} MHz sampling; standoff ${fmt(a.surface_standoff_mm)} mm. A full-support output retains ${source.shape[0]-2} × ${source.shape[1]-2} positions.`;
      if(!this.manifest){this.support=null;$('support-note').textContent='Estimate this source to freeze the exact retained extent and physical support offsets.';this.drawSupport();}
    }catch(error){if(error.name!=='AbortError'&&controller===this.sourceController){$('source-note').textContent=error.message;this.message(error.message,true);}}
  }
  async estimate(){if(!$('form').reportValidity()||!this.source){if(!this.source)this.message('Select an available completed causal source first.',true);return;}this.estimateController?.abort();const payload=this.payload(),key=JSON.stringify(payload),controller=this.estimateController=new AbortController();this.estimateKey=null;$('start').disabled=true;this.message('Checking full-support coordinates, inherited semantics and resources…');
    try{const estimate=await this.request(`${API}/estimate`,payload,controller.signal);if(controller!==this.estimateController||key!==JSON.stringify(this.payload()))return;this.estimateKey=key;this.estimateResult=estimate;this.support=estimate;this.supportMode='draft';$('support-panel').open=true;this.describeSupport(estimate);const r=estimate.resources||estimate;$('estimate').textContent=`${estimate.shape.join(' × ')} output samples (y, x, time). Saved output ${bytes(r.total_bytes??estimate.total_bytes)}; peak owned workspace ${bytes(r.estimated_peak_bytes??estimate.estimated_peak_bytes)}.${r.output_complex_samples!=null?` ${Number(r.output_complex_samples).toLocaleString()} complex outputs.`:''} Complete rows are published only after arithmetic and magnitude bounds pass.`;$('estimate-json').textContent=JSON.stringify(estimate,null,2);$('estimate-detail').hidden=false;$('start').disabled=this.starting===true;this.message('Support estimate ready. The one-cell source ring is consumed; it is not retained as an output border.');}
    catch(error){if(error.name!=='AbortError'&&controller===this.estimateController){$('estimate').textContent=error.message;this.message(`Estimate rejected: ${error.message}. Inputs retained.`,true);}}
  }
  async start(){if(this.starting||!$('form').reportValidity())return;if(this.estimateKey!==JSON.stringify(this.payload())){await this.estimate();if(this.estimateKey!==JSON.stringify(this.payload()))return;}this.starting=true;$('start').disabled=true;try{const job=await this.request(`${API}/jobs`,this.payload());this.pending=idOf(job);$('process-panel').open=false;this.message('Derived observation queued with frozen source, weights and error ceiling.');await this.refresh();}catch(error){this.message(`Processing could not start: ${error.message}`,true);}finally{this.starting=false;$('start').disabled=!this.estimateKey;}}
  async refresh(){clearTimeout(this.pollTimer);this.catalogController?.abort();const controller=this.catalogController=new AbortController();try{const [sources,jobs,datasets]=await Promise.all([this.request('/api/v2/datasets',null,controller.signal),this.request(`${API}/jobs`,null,controller.signal),this.request(`${API}/datasets`,null,controller.signal)]);if(controller!==this.catalogController)return;this.sources=sources.datasets.filter(d=>d.kind===SOURCE&&complete(d));this.jobs=jobs.jobs.filter(d=>d.kind===KIND);this.datasets=datasets.datasets.filter(d=>d.kind===KIND);const previous=$('source').value||this.openSource||'';$('source').replaceChildren(new Option('Select a causal volume',''));for(const s of this.sources)$('source').add(new Option(`${s.name} · ${idOf(s).slice(0,8)}`,idOf(s)));$('source').value=previous;this.openSource=null;this.renderCatalog();const finished=this.datasets.find(d=>idOf(d)===this.pending&&complete(d));if(finished){this.pending=null;await this.selectDataset(idOf(finished));}}
    catch(error){if(error.name!=='AbortError'&&controller===this.catalogController)this.message(`Observation catalog unavailable: ${error.message}. Existing saved output remains visible.`,true);}
    finally{if(controller===this.catalogController&&$('dialog').open)this.pollTimer=setTimeout(()=>this.refresh(),this.jobs.some(j=>active(j.status||j.state))?1200:7000);}}
  renderCatalog(){
    const js=JSON.stringify(this.jobs);if(js!==this.jobsSignature){this.jobsSignature=js;$('jobs').replaceChildren();if(!this.jobs.length)$('jobs').textContent='No derived jobs yet.';for(const job of this.jobs.slice(0,8)){const row=document.createElement('div'),title=document.createElement('strong'),note=document.createElement('p'),progress=document.createElement('progress');row.className='ob-job';row.dataset.jobId=job.id;const state=job.status||job.state;title.textContent=`${state} · ${job.completed_rows||0}/${job.total_rows||'—'} committed output rows`;note.className='ob-hint';note.textContent=job.error||(!job.completed_rows&&active(state)?'Verifying source support and processing bounded time blocks; no output row committed.':`Job ${job.id.slice(0,8)}`);progress.max=job.total_rows||1;progress.value=job.completed_rows||0;row.append(title,note,progress);const action=active(state)?'cancel':['cancelled','interrupted','failed'].includes(state)?'resume':null;if(action){const button=document.createElement('button');button.className='small';button.dataset.action=action;button.textContent=action==='cancel'?'Cancel processing':'Resume frozen processing';button.onclick=async()=>{button.disabled=true;try{const updated=await this.request(`${API}/jobs/${job.id}/${action}`,{});if(action==='resume')this.pending=idOf(updated);this.message(action==='cancel'?'Cancellation requested at a bounded checkpoint. Partial rows are not committed; completed output rows are preserved.':'Resuming the frozen source and operator. Verified committed output rows are skipped.');await this.refresh();}catch(error){this.message(error.message,true);button.disabled=false;}};row.append(button);}$('jobs').append(row);}}
    const ds=JSON.stringify([this.datasets,idOf(this.manifest)]);if(ds===this.datasetsSignature)return;this.datasetsSignature=ds;$('datasets').replaceChildren();if(!this.datasets.length)$('datasets').textContent='No saved observations yet.';for(const d of this.datasets){const button=document.createElement('button');button.className='ob-dataset';button.dataset.datasetId=idOf(d);button.disabled=!complete(d);button.setAttribute('aria-pressed',String(idOf(d)===idOf(this.manifest)));const title=document.createElement('strong'),detail=document.createElement('span');title.textContent=d.name||'Finite coherent observation';detail.textContent=`${d.shape.join(' × ')} · ${d.status||d.state} · ${idOf(d).slice(0,8)}`;button.append(title,detail);button.onclick=()=>this.selectDataset(idOf(d));$('datasets').append(button);}
  }
  async selectDataset(id){this.viewController?.abort();this.selectionController?.abort();this.selecting=true;const controller=this.selectionController=new AbortController();this.message('Reading the saved observation independently of its parent…');try{const m=await this.request(`${API}/datasets/${id}`,null,controller.signal);if(controller!==this.selectionController||!$('dialog').open)return;if(m.kind!==KIND||!complete(m))throw new Error('Open a completed coherent observation.');this.manifest=m;this.view=null;$('viewer').hidden=true;const [ny,nx,nt]=m.shape,estimate=m.estimate||m,coords=m.coordinates||estimate.coordinates;const times=m.time_range_us||[coords.time_us[0],coords.time_us.at(-1)];this.cursor={x_index:Math.floor(nx/2),y_index:Math.floor(ny/2),time_index:Math.floor(nt/4)};this.gate={start_us:times[0],end_us:times[1],mode:'peak_envelope'};for(const [key,max] of [['x',nx-1],['y',ny-1],['time',nt-1]])$(key).max=max;$('gate-start').value=times[0];$('gate-end').value=times[1];$('gate-mode').value='peak_envelope';$('dataset-name').textContent=m.name||m.request.name||'Saved coherent observation';const a=m.source_summary?.acquisition||estimate.source_summary?.acquisition||m.source_manifest?.request?.acquisition||{};$('dataset-detail').textContent=`${m.shape.join(' × ')} saved samples (y, x, time). Inherited ${fmt(a.center_frequency_mhz)} MHz gamma, bandwidth ${fmt(a.fractional_bandwidth)}, order ${fmt(a.gamma_order)}; ${fmt(a.sample_rate_mhz)} MHz sampling. Source ${m.source_dataset_id||m.request.source_dataset_id}.`;$('export').href=`${API}/datasets/${id}/export`;this.support=estimate;this.supportMode='saved';this.describeSupport(estimate);$('support-panel').open=false;$('provenance-json').textContent=JSON.stringify({dataset_id:id,request:m.request,source_summary:m.source_summary||estimate.source_summary,metadata:m.metadata,operator:m.operator||estimate.operator,source_indices:m.source_indices||estimate.source_indices,estimate:estimate.resources,certificates:m.certificates||m.certificate},null,2);$('empty').hidden=true;if(innerWidth<=800)$('process-panel').open=false;try{localStorage.setItem('vm-last-observation',id);}catch{}this.renderCatalog();this.selecting=false;await this.loadView();}catch(error){if(error.name!=='AbortError')this.message(`Saved observation unavailable: ${error.message}`,true);}finally{if(controller===this.selectionController)this.selecting=false;}}
  async useSaved(){if(!this.manifest)return;const r=this.manifest.request;$('name').value=r.name||'';$('tolerance').value=r.absolute_tolerance;$('process-panel').open=true;await this.selectSource(r.source_dataset_id);if(idOf(this.source)===r.source_dataset_id)this.message('Frozen source and ceiling staged as a new draft. Current specimen state and saved output are unchanged.');}
  describeSupport(s){$('support-note').textContent=`${this.supportMode==='saved'?'Saved':'Estimated'} ${s.source_shape?.[1]} × ${s.source_shape?.[0]} source positions become ${s.shape?.[1]} × ${s.shape?.[0]} retained positions. One source cell is removed on every side; all nine neighbors remain available. Display cells use frozen midpoint edges; sample centers are copied exactly.`;const e=s.extent_mm,se=s.source_extent_mm;$('source-extent').textContent=se?`Source x ${fmt(se[0])}–${fmt(se[1])}, y ${fmt(se[2])}–${fmt(se[3])} mm.`:'';$('output-extent').textContent=e?`Retained x ${fmt(e[0])}–${fmt(e[1])}, y ${fmt(e[2])}–${fmt(e[3])} mm.`:'';$('support-offsets').textContent='The same index stencil has a different physical span at a different source pitch. Actual neighboring centers and source indices remain authoritative; decimal-grid adjacent differences may vary by rounding. Sampling pitch and filter support do not establish physical resolution.';this.drawSupport();}
  drawSupport(){for(const target of ['source','interior'])drawSupport($( `support-${target}`),this.support,target);}
  loadViewSoon(){if(this.selecting)return;this.viewController?.abort();clearTimeout(this.viewTimer);this.viewTimer=setTimeout(()=>this.loadView(),100);}
  async loadView(){if(!this.manifest||!this.gate||!$('dialog').open)return;this.viewController?.abort();const controller=this.viewController=new AbortController(),id=idOf(this.manifest),product=this.product,query=new URLSearchParams({...this.cursor,product,gate_start_us:this.gate.start_us,gate_end_us:this.gate.end_us,gate_mode:this.gate.mode});this.message('Reading saved observation samples and their five bounds…');try{const v=await this.request(`${API}/datasets/${id}/view?${query}`,null,controller.signal);if(controller!==this.viewController||id!==idOf(this.manifest))return;this.view={...v,product};this.cursor={x_index:v.cursor.x_index,y_index:v.cursor.y_index,time_index:v.cursor.time_index};$('viewer').hidden=false;for(const key of ['x','y','time']){$(key).value=this.cursor[`${key}_index`];$(`${key}-value`).textContent=`${fmt(v.cursor[key==='time'?'time_us':`${key}_mm`])} ${key==='time'?'µs':'mm'}`;}$('xy-caption').textContent=`${products[product]} · ${fmt(v.cursor.time_us)} µs`;$('xt-caption').textContent=`y ${fmt(v.cursor.y_mm)} mm`;$('yt-caption').textContent=`x ${fmt(v.cursor.x_mm)} mm`;$('cscan-caption').textContent=`${v.gate.mode==='rms_rf'?'RMS real pressure':'Peak magnitude'} · ${fmt(v.gate.actual_start_us??v.gate.start_us)}–${fmt(v.gate.actual_end_us??v.gate.end_us)} µs`;this.renderBounds();this.draw();this.message('Saved observation ready. Cursor, gates and windows read retained output; no source or propagation is required.');}catch(error){if(error.name!=='AbortError'&&controller===this.viewController){this.message(`Saved view rejected: ${error.message}. Previous accepted view retained.`,true);}}}
  renderBounds(){const c=this.view.certificate;$('bound-note').textContent=`Uniform over every retained time center. Frozen requested ceiling ${fmt(c.tolerance??c.requested_tolerance??this.manifest.request.absolute_tolerance)}. Source propagation and exact-mixing conversion errors are separate; magnitude is enclosed after mixing.`;$('bound-table').replaceChildren();const table=document.createElement('table'),head=table.createTHead().insertRow();for(const title of ['Component','Selected output column','Volume maximum']){const cell=document.createElement('th');cell.textContent=title;head.append(cell);}const body=table.createTBody();for(const [key,title] of bounds){const row=body.insertRow();row.dataset.bound=key;row.insertCell().textContent=title;for(const value of [c.selected_bounds[key],(c.max_bounds||c.volume_max_bounds)?.[key]]){const cell=row.insertCell();cell.textContent=fmt(value);cell.dataset.value=value;cell.title=value==null?'Not returned':Number(value).toPrecision(17);}}$('bound-table').append(table);}
  draw(){if(!this.view||!$('dialog').open)return;const v=this.view,c=v.cursor,p=v.product;$('view-note').textContent=`${p==='envelope'?'Recomputed magnitude maps 0':'Signed maps −'+fmt(this.ceiling)} to ${fmt(this.ceiling)}; gate map 0 to ${fmt(this.ceiling)}, trace ±${fmt(this.ceiling)}. Display clipping only. Sections use nearest saved time centers without pooling; spatial axes scale independently.`;for(const key of ['xy','cscan','xt','yt'])drawCausalMap($(key),v[key],['xy','cscan'].includes(key)?['x (mm)','y (mm)']:[key==='xt'?'x (mm)':'y (mm)','Time (µs)'],['xy','cscan'].includes(key)?[c.x_mm,c.y_mm]:[key==='xt'?c.x_mm:c.y_mm,c.time_us],this.ceiling,key==='cscan'?'envelope':p);const boundKey=$('bound-product').value,boundMap=v.bound_maps?.[boundKey]||v.certificate.maps?.[boundKey];if(boundMap){const maximum=Math.max(0,...boundMap.flat()),scale=maximum||1;$('bound-scale').textContent=`${bounds.find(([key])=>key===boundKey)[1]}: color scale 0 to ${fmt(maximum)}; every saved time center shares this spatial bound.${maximum===0?' All values are zero; display uses a unit fallback scale.':''}`;drawCausalMap($('bound-map'),{image:boundMap,extent_mm:v.extent_mm||v.xy.extent_mm},['x (mm)','y (mm)'],[c.x_mm,c.y_mm],scale,'envelope');Object.assign($('bound-map').dataset,{bound:boundKey,maximum});}const a=v.ascan,curves=[{values:a.rf,color:'#2864d7'},{values:a.envelope,color:'#368470'}];if($('quadrature').checked)curves.push({values:a.imaginary,color:'#8560aa',dashed:true});drawLayeredCurve($('ascan'),a.time_us,curves,{range:[-this.ceiling,this.ceiling],labelX:'Inherited recording time (µs)',labelY:'Relative pressure',cursor:c.time_us});const t=c.time_index;$('readout').textContent=`Output index x${c.x_index}, y${c.y_index} uses source center x${c.source_x_index}, y${c.source_y_index}. Actual x ${fmt(c.x_mm)} mm, y ${fmt(c.y_mm)} mm, t ${fmt(c.time_us)} µs: real ${fmt(a.rf[t])}, imaginary ${fmt(a.imaginary[t])}, recomputed magnitude ${fmt(a.envelope[t])}. Display limits leave the stored values unchanged.`;Object.assign($('readout').dataset,{xIndex:c.x_index,yIndex:c.y_index,timeIndex:t,sourceXIndex:c.source_x_index,sourceYIndex:c.source_y_index,xMm:c.x_mm,yMm:c.y_mm,timeUs:c.time_us,rf:a.rf[t],imaginary:a.imaginary[t],envelope:a.envelope[t]});}
  pick(id,event){if(!this.view)return;const canvas=$(id),p=id==='ascan'?canvas._layeredPlot:canvas._causalPlot;if(!p)return;const r=canvas.getBoundingClientRect(),u=(event.clientX-r.left-p.left)/p.width,v=(event.clientY-r.top-p.top)/p.height;if(u<0||u>1||v<0||v>1)return;const [ny,nx,nt]=this.manifest.shape,at=(f,n)=>Math.min(n-1,Math.max(0,Math.floor(f*n)));if(id==='ascan')this.cursor.time_index=Math.round(u*(nt-1));else if(['xy','cscan','bound-map'].includes(id)){this.cursor.x_index=at(u,nx);this.cursor.y_index=at(v,ny);}else{this.cursor[id==='xt'?'x_index':'y_index']=at(u,id==='xt'?nx:ny);this.cursor.time_index=Math.round(v*(nt-1));}this.loadViewSoon();}
  keyboard(id,event){if(!this.view||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();const horizontal=['ArrowLeft','ArrowRight'].includes(event.key),key=id==='ascan'?'time_index':['xy','cscan','bound-map'].includes(id)?(horizontal?'x_index':'y_index'):horizontal?(id==='xt'?'x_index':'y_index'):'time_index',axis={x_index:1,y_index:0,time_index:2}[key],delta=['ArrowLeft','ArrowUp'].includes(event.key)?-1:1;this.cursor[key]=Math.min(this.manifest.shape[axis]-1,Math.max(0,this.cursor[key]+delta*(event.shiftKey?10:1)));this.loadViewSoon();}
}

function drawSupport(canvas,estimate,mode){const w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.fillStyle='#f8fbfd';ctx.fillRect(0,0,w,h);ctx.font='11px "Segoe UI",sans-serif';ctx.fillStyle='#57728a';if(!estimate?.source_shape||!estimate.extent_mm||!estimate.source_extent_mm){ctx.textAlign='center';ctx.fillText('Estimate the source to view frozen support.',w/2,h/2);return;}
 const [ny,nx]=estimate.source_shape,[x0,x1,y0,y1]=estimate.source_extent_mm,e=estimate.extent_mm,left=58,top=14,width=w-78,height=h-58,px=x=>left+(x-x0)/(x1-x0)*width,py=y=>top+(y-y0)/(y1-y0)*height;
 ctx.fillStyle=mode==='source'?'#d7e0e7':'#f4f7fa';ctx.fillRect(left,top,width,height);ctx.fillStyle='#bad7e7';ctx.fillRect(px(e[0]),py(e[2]),px(e[1])-px(e[0]),py(e[3])-py(e[2]));ctx.strokeStyle='#eaf2f8';ctx.lineWidth=.5;
 for(let i=0;i<=nx;i++){ctx.beginPath();ctx.moveTo(left+i/nx*width,top);ctx.lineTo(left+i/nx*width,top+height);ctx.stroke();}for(let i=0;i<=ny;i++){ctx.beginPath();ctx.moveTo(left,top+i/ny*height);ctx.lineTo(left+width,top+i/ny*height);ctx.stroke();}
 ctx.strokeStyle='#8aa6ba';ctx.lineWidth=1;ctx.strokeRect(left,top,width,height);ctx.strokeStyle='#2f719f';ctx.lineWidth=2;ctx.strokeRect(px(e[0]),py(e[2]),px(e[1])-px(e[0]),py(e[3])-py(e[2]));ctx.fillStyle='#365d7b';ctx.textAlign='center';ctx.fillText(`${nx} source X positions; ${nx-2} retained`,left+width/2,h-5);ctx.fillText(fmt(x0),left,top+height+16);ctx.fillText(fmt(x1),left+width,top+height+16);ctx.textAlign='right';ctx.fillText(fmt(y0),left-5,top+5);ctx.fillText(fmt(y1),left-5,top+height);ctx.save();ctx.translate(12,top+height/2);ctx.rotate(-Math.PI/2);ctx.textAlign='center';ctx.fillText(`${ny} source Y; ${ny-2} retained`,0,0);ctx.restore();Object.assign(canvas.dataset,{sourceRows:ny,sourceColumns:nx,rows:estimate.shape[0],columns:estimate.shape[1],extent:JSON.stringify(e),sourceExtent:JSON.stringify(estimate.source_extent_mm)});
}
