import './reconstruction.css';

const el=id=>document.getElementById(`ct-${id}`);
const fmt=value=>Number(value).toLocaleString(undefined,{maximumFractionDigits:4});
const bytes=value=>value>=1073741824?`${(value/1073741824).toFixed(2)} GiB`:value>=1048576?`${(value/1048576).toFixed(1)} MiB`:`${(value/1024).toFixed(1)} KiB`;
const field=(id,label,value,min,max,step='any')=>`<label for="ct-${id}">${label}<input id="ct-${id}" type="number" value="${value}" min="${min}" max="${max}" step="${step}" required></label>`;
const completed=item=>item.complete===true||item.state==='completed';
const active=status=>['queued','running','cancel_requested','cancelling','pending','resuming'].includes(status);
const kind='xray_reconstruction';
const axes={xy:['x','y'],xz:['x','z'],yz:['y','z']};

export class ReconstructionWorkspace {
  constructor({request}) {
    this.request=request;this.jobs=[];this.datasets=[];this.sources=[];this.cursor={x_index:0,y_index:0,z_index:0};this.window=[-.05,1];
    document.body.insertAdjacentHTML('beforeend',`
      <dialog id="ct-dialog" aria-labelledby="ct-title" aria-describedby="ct-intro">
        <header class="ct-header"><div><h2 id="ct-title">CT reconstruction</h2><p id="ct-intro">Reconstruct saved parallel-beam projections into a volume of attenuation.</p></div><button id="ct-close" class="quiet" aria-label="Close CT reconstruction">✕</button></header>
        <div class="ct-layout">
          <aside class="ct-acquisition" aria-label="Reconstruction settings and saved volumes">
            <details id="ct-new-panel" open><summary>New reconstruction</summary>
              <form id="ct-form">
                <label class="ct-source-label" for="ct-source">Saved X-ray source<select id="ct-source"><option value="">Loading completed projections…</option></select></label>
                <p id="ct-source-detail" class="ct-hint">Uses the frozen source specimen and acquisition, independently of the current preview.</p>
                <fieldset><legend>Reconstruction grid</legend><div class="ct-fields">${field('nx','X samples',96,16,256,1)}${field('ny','Y samples',64,16,256,1)}${field('nz','Z samples',64,16,256,1)}</div><p class="ct-hint">Sample pitch is a grid choice, not measured instrument resolution.</p></fieldset>
                <fieldset><legend>Physical bounds</legend><label class="ct-check"><input id="ct-full-bounds" type="checkbox" checked>Full frozen specimen bounds</label><div class="ct-fields">${field('xmin','X minimum (mm)',0,0,300)}${field('xmax','X maximum (mm)',1,0,300)}${field('ymin','Y minimum (mm)',0,0,300)}${field('ymax','Y maximum (mm)',1,0,300)}${field('zmin','Z minimum (mm)',0,0,300)}${field('zmax','Z maximum (mm)',1,0,300)}</div></fieldset>
                <fieldset><legend>Filtered backprojection</legend><div class="ct-fields"><label for="ct-filter">Filter<select id="ct-filter"><option value="hann">Hann</option><option value="ram_lak">Ram–Lak</option></select></label>${field('frequency_cutoff','Frequency cutoff',1,.1,1,.05)}</div><p class="ct-hint">Cutoff is a fraction of the detector Nyquist frequency. Requires at least 16 views spanning 180° or 360°.</p></fieldset>
                <fieldset><legend>Missing measurements</legend><label class="ct-source-label" for="ct-invalid_policy">Zero-count logarithms<select id="ct-invalid_policy"><option value="interpolate">Interpolate invalid detector samples</option><option value="reject">Reject invalid samples</option></select></label><label class="ct-source-label" for="ct-truncation_policy">Detector truncation<select id="ct-truncation_policy"><option value="reject">Reject truncated source</option><option value="allow">Allow truncation with artifacts</option></select></label><p id="ct-policy-note" class="ct-hint"></p></fieldset>
                <div id="ct-estimate" class="ct-estimate" aria-live="polite">Select a completed X-ray source.</div><details id="ct-warnings" hidden><summary>Reconstruction notes</summary><ul></ul></details><button id="ct-estimate-btn" class="small" type="button">Estimate reconstruction</button><button id="ct-start" class="primary" type="submit" disabled>Start CT reconstruction</button>
              </form>
            </details>
            <section class="ct-jobs"><h3>Reconstruction jobs</h3><div id="ct-jobs-list"></div></section>
            <section class="ct-saved"><div class="ct-list-heading"><h3>Saved CT volumes</h3><button id="ct-refresh-list" class="quiet" aria-label="Refresh saved CT volumes">↻</button></div><div id="ct-datasets"></div></section>
          </aside>
          <main class="ct-inspector">
            <div id="ct-message" class="ct-message" role="status" aria-live="polite">Choose saved projections to reconstruct, or open an existing CT volume.</div>
            <div id="ct-empty" class="ct-empty"><svg viewBox="0 0 170 130" fill="none" aria-hidden="true"><path d="m30 35 65-22 45 33-65 24Zm0 0v60l45 24V70m65-24v59l-65 14M30 65l65-22 45 33M62 24v58l46 29"/></svg><h3>From angular measurements to physical slices</h3><p>Inspect attenuation in linked XY, XZ and YZ planes. Each saved volume retains its source acquisition, reconstruction settings and geometric angular support.</p><p class="ct-hint">Synthetic parallel-beam CT. No cone-beam, limited-angle or experimental calibration support.</p></div>
            <div id="ct-viewer" hidden>
              <div class="ct-dataset-heading"><div><h3 id="ct-dataset-name"></h3><p id="ct-dataset-detail"></p></div><a id="ct-export" class="ct-download" href="#" download>Download Zarr archive</a></div>
              <div class="ct-controls">${['x','y','z'].map(axis=>`<label for="ct-${axis}">${axis.toUpperCase()} position <output id="ct-${axis}-value"></output><input id="ct-${axis}" type="range" min="0" max="0" step="1" value="0"></label>`).join('')}<label for="ct-window-min">Display minimum (mm⁻¹)<input id="ct-window-min" type="number" step="any" value="-.05"></label><label for="ct-window-max">Display maximum (mm⁻¹)<input id="ct-window-max" type="number" step="any" value="1"></label></div>
              <p id="ct-view-note" class="ct-view-note">Reading saved attenuation slices.</p><details id="ct-saved-notes" class="ct-saved-notes" hidden><summary>Saved reconstruction notes</summary><ul></ul></details>
              <div class="ct-slice-grid">${Object.keys(axes).map(plane=>`<section class="ct-plot ct-${plane}"><div><h4>${plane.toUpperCase()} section</h4><span id="ct-${plane}-caption"></span></div><canvas id="ct-${plane}" tabindex="0" role="img" aria-label="${plane.toUpperCase()} attenuation section; click or use arrow keys to move the linked cursor"></canvas></section>`).join('')}</div>
              <div class="ct-cursor"><strong id="ct-cursor-position"></strong><span id="ct-cursor-attenuation"></span><span id="ct-cursor-coverage"></span></div>
              <div class="ct-legend"><output id="ct-window-low"></output><i></i><output id="ct-window-high"></output><span>mm⁻¹</span><span class="ct-coverage-key"><b class="none"></b>No geometric support</span><span class="ct-coverage-key"><b class="partial"></b>Partial geometric support</span></div>
              <p class="ct-hint">Gray masks show angular support below 100%; they are not uncertainty or accuracy estimates. Stored attenuation can be negative. Each panel fits its axes independently; use the millimeter labels for dimensions.</p><p id="ct-provenance" class="ct-hint"></p>
            </div>
          </main>
        </div>
      </dialog>`);
    el('close').addEventListener('click',()=>el('dialog').close());
    el('dialog').addEventListener('close',()=>{for(const key of ['pollTimer','estimateTimer','viewTimer'])clearTimeout(this[key]);for(const key of ['catalogController','sourceController','selectionController','estimateController','viewController'])this[key]?.abort();});
    el('refresh-list').addEventListener('click',()=>this.catalog());
    el('source').addEventListener('change',()=>this.selectSource(el('source').value));
    el('form').addEventListener('input',event=>{if(event.target!==el('source'))this.changed();});
    el('estimate-btn').addEventListener('click',()=>this.estimate());
    el('form').addEventListener('submit',event=>{event.preventDefault();this.start();});
    for(const axis of ['x','y','z'])el(axis).addEventListener('input',event=>{this.cursor[`${axis}_index`]=Number(event.target.value);this.viewSoon();});
    for(const id of ['window-min','window-max'])el(id).addEventListener('input',()=>{const min=Number(el('window-min').value),max=Number(el('window-max').value);if(!Number.isFinite(min)||!Number.isFinite(max)||min>=max){this.message('Display maximum must be greater than the minimum.',true);return;}this.window=[min,max];this.message('Display limits applied to saved attenuation.');this.draw();});
    for(const plane of Object.keys(axes)){el(plane).addEventListener('click',event=>this.pick(plane,event));el(plane).addEventListener('keydown',event=>this.move(plane,event));}
    new ResizeObserver(()=>this.draw()).observe(document.querySelector('.ct-inspector'));
  }
  open(){if(el('dialog').open)return;el('dialog').showModal();this.catalog();if(this.source)this.changed();else if(el('source').value)this.selectSource(el('source').value);if(this.manifest)this.loadView();requestAnimationFrame(()=>this.draw());}
  message(text,error=false){el('message').textContent=text;el('message').classList.toggle('error',error);}
  payload(){const reconstruction={...Object.fromEntries(['nx','ny','nz','frequency_cutoff'].map(key=>[key,Number(el(key).value)])),...Object.fromEntries(['filter','invalid_policy','truncation_policy'].map(key=>[key,el(key).value]))};if(!el('full-bounds').checked)reconstruction.bounds_mm=['xmin','xmax','ymin','ymax','zmin','zmax'].map(id=>Number(el(id).value));return {kind,source_dataset_id:this.source?.dataset_id||this.source?.id,reconstruction};}
  changed(){this.estimateKey=null;el('start').disabled=true;this.estimateController?.abort();clearTimeout(this.estimateTimer);for(const id of ['xmin','xmax','ymin','ymax','zmin','zmax'])el(id).disabled=el('full-bounds').checked;el('policy-note').textContent=`${el('invalid_policy').value==='interpolate'?'Zero-count log samples are interpolated before filtering; missing measurements are not recovered.':'Any invalid zero-count log sample prevents reconstruction.'} ${el('truncation_policy').value==='allow'?'Truncated data can produce artifacts and incomplete angular support.':'Sources with detector truncation are rejected.'}`;el('estimate').textContent=this.source?'Settings changed. Estimating reconstruction…':'Select a completed X-ray source.';if(this.source)this.estimateTimer=setTimeout(()=>this.estimate(),350);}
  async selectSource(id){this.sourceController?.abort();this.estimateController?.abort();this.source=null;this.changed();if(!id)return;const controller=this.sourceController=new AbortController();el('source-detail').textContent='Reading frozen source acquisition…';try{const source=await this.request(`/api/v2/datasets/${encodeURIComponent(id)}`,null,controller.signal);if(controller!==this.sourceController||!el('dialog').open)return;this.source=source;const size=source.request?.twin?.size_mm||source.source_manifest?.request?.twin?.size_mm;if(!size)throw new Error('The source is missing its frozen specimen bounds.');for(const [axis,index] of [['x',0],['y',1],['z',2]]){el(`${axis}min`).value=0;el(`${axis}max`).value=size[index];el(`${axis}min`).max=size[index];el(`${axis}max`).max=size[index];}el('source-detail').textContent=`${source.name}. ${source.shape[0]} views over ${fmt(source.acquisition.angle_span_deg)}°. Frozen specimen ${size.map(fmt).join(' × ')} mm. Source ${id}. The current digital twin is not used.`;this.changed();}catch(error){if(error.name!=='AbortError'){this.source=null;el('source-detail').textContent=error.message;this.message(error.message,true);}}}
  async estimate(){clearTimeout(this.estimateTimer);if(!this.source||!el('dialog').open)return;if(!el('form').checkValidity()){el('estimate').textContent='Correct the reconstruction fields before estimating.';return;}const body=this.payload(),key=JSON.stringify(body);if(body.reconstruction.bounds_mm?.some((value,index,array)=>index%2===0&&value>=array[index+1])){el('estimate').textContent='Each bounds maximum must exceed its minimum.';return;}this.estimateController?.abort();const controller=this.estimateController=new AbortController();el('start').disabled=true;try{const result=await this.request('/api/v2/estimate',body,controller.signal);if(controller!==this.estimateController||key!==JSON.stringify(this.payload()))return;this.estimateKey=key;el('estimate').textContent=`${result.shape.join(' × ')} samples (Z, Y, X). Stored attenuation and support: ${bytes(result.total_bytes)}. Estimated peak memory: ${bytes(result.estimated_peak_bytes)}.${result.estimated_temporary_bytes!==undefined?` Temporary disk workspace: ${bytes(result.estimated_temporary_bytes)}.`:''}${result.voxel_pitch_mm?` Pitch X/Y/Z: ${result.voxel_pitch_mm.map(value=>fmt(value*1000)).join(' / ')} µm.`:''}`;el('warnings').hidden=!result.warnings?.length;el('warnings').querySelector('ul').replaceChildren();for(const warning of result.warnings||[]){const li=document.createElement('li');li.textContent=warning;el('warnings').querySelector('ul').append(li);}el('start').disabled=Boolean(this.starting);}catch(error){if(error.name!=='AbortError'&&controller===this.estimateController){this.estimateKey=null;el('estimate').textContent=error.message;}}}
  async start(){if(this.starting||!this.source||!el('form').reportValidity())return;const body=this.payload();if(this.estimateKey!==JSON.stringify(body)){await this.estimate();if(this.estimateKey!==JSON.stringify(body))return;}this.starting=true;el('start').disabled=true;el('start').textContent='Submitting…';try{const job=await this.request('/api/v2/jobs',body);this.pendingId=job.dataset_id;el('new-panel').open=false;this.message('Reconstruction submitted. The saved source and reconstruction settings are frozen.');await this.catalog();}catch(error){this.message(error.message,true);}finally{this.starting=false;el('start').textContent='Start CT reconstruction';el('start').disabled=!this.estimateKey;}}
  async catalog(){clearTimeout(this.pollTimer);this.catalogController?.abort();const controller=this.catalogController=new AbortController();try{const [jobs,data]=await Promise.all([this.request('/api/v2/jobs',null,controller.signal),this.request('/api/v2/datasets',null,controller.signal)]);if(controller!==this.catalogController)return;this.jobs=jobs.jobs.filter(item=>item.kind===kind);this.datasets=data.datasets.filter(item=>item.kind===kind);this.sources=data.datasets.filter(item=>item.kind==='xray_projection_volume'&&completed(item));this.renderCatalog();const pending=this.datasets.find(item=>(item.dataset_id||item.id)===this.pendingId&&completed(item));if(pending){this.pendingId=null;await this.select(pending.dataset_id||pending.id);}else if(!this.manifest&&!this.selecting){let saved;try{saved=localStorage.getItem('virtual-microscopy-last-ct');}catch{}const found=this.datasets.find(item=>completed(item)&&(item.dataset_id||item.id)===saved)||this.datasets.find(completed);if(found)await this.select(found.dataset_id||found.id);}}catch(error){if(error.name!=='AbortError')this.message(`CT catalog unavailable: ${error.message}`,true);}finally{if(controller===this.catalogController&&el('dialog').open)this.pollTimer=setTimeout(()=>this.catalog(),this.jobs.some(job=>active(job.status))?1200:6000);}}
  renderCatalog(){const ordered=list=>[...list].sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||'')));const sourceSignature=JSON.stringify(this.sources.map(source=>[source.dataset_id||source.id,source.name,source.shape,source.acquisition?.angle_span_deg]));if(sourceSignature!==this.sourceSignature){this.sourceSignature=sourceSignature;const selected=el('source').value;el('source').replaceChildren();if(!this.sources.length){const option=document.createElement('option');option.value='';option.textContent='Acquire X-ray projections first';el('source').append(option);}for(const source of ordered(this.sources)){const option=document.createElement('option'),id=source.dataset_id||source.id;option.value=id;option.textContent=`${source.name} — ${source.shape[0]} views — ${id.slice(0,8)}`;el('source').append(option);}el('source').value=this.sources.some(source=>(source.dataset_id||source.id)===selected)?selected:ordered(this.sources).find(source=>source.shape[0]>=16&&[180,360].includes(source.acquisition?.angle_span_deg))?.dataset_id||el('source').options[0]?.value||'';if(!this.source&&el('source').value)this.selectSource(el('source').value);}
    const signature=JSON.stringify([this.jobs,this.datasets,this.manifest?.dataset_id]);if(signature===this.catalogSignature)return;this.catalogSignature=signature;el('jobs-list').replaceChildren();el('datasets').replaceChildren();if(!this.jobs.length)el('jobs-list').textContent='No reconstruction jobs yet.';
    for(const job of ordered(this.jobs).slice(0,8)){const row=document.createElement('div');row.className='ct-job';row.dataset.jobId=job.id;const title=document.createElement('strong'),done=job.completed_units??0,total=job.total_units??1;title.textContent=`${job.status.replaceAll('_',' ')} · ${done}/${total} slices`;const progress=document.createElement('progress');progress.max=total;progress.value=done;progress.setAttribute('aria-label',`Reconstruction ${job.id} progress`);row.append(title,progress);if(job.error){const error=document.createElement('p');error.textContent=job.error;row.append(error);}const action=active(job.status)?'cancel':['cancelled','interrupted','failed'].includes(job.status)?'resume':null;if(action){const button=document.createElement('button');button.className='small';button.dataset.action=action;button.textContent=action==='cancel'?'Cancel reconstruction':'Resume reconstruction';button.addEventListener('click',async()=>{button.disabled=true;try{const result=await this.request(`/api/v2/jobs/${encodeURIComponent(job.id)}/${action}`,{});if(action==='resume')this.pendingId=result.dataset_id;this.message(action==='cancel'?'Cancellation requested. Completed slices remain saved.':'Resuming the saved reconstruction.');await this.catalog();}catch(error){button.disabled=false;this.message(error.message,true);}});row.append(button);}el('jobs-list').append(row);}
    if(!this.datasets.length)el('datasets').textContent='No saved CT volumes.';for(const data of ordered(this.datasets)){const id=data.dataset_id||data.id,button=document.createElement('button');button.className='ct-dataset';button.dataset.datasetId=id;button.disabled=!completed(data);button.setAttribute('aria-pressed',String(id===(this.manifest?.dataset_id||this.manifest?.id)));for(const [tag,text] of [['strong',data.name],['span',`${data.shape.join(' × ')} · ${data.state}`],['span',`${new Date(data.created_at).toLocaleString()} · ${id.slice(0,8)}`]]){const child=document.createElement(tag);child.textContent=text;button.append(child);}button.addEventListener('click',()=>this.select(id));el('datasets').append(button);}}
  async select(id){this.selectionController?.abort();this.viewController?.abort();const controller=this.selectionController=new AbortController();this.selecting=true;el('view-note').textContent='Opening saved CT volume…';for(const axis of ['x','y','z'])el(axis).disabled=true;try{const data=await this.request(`/api/v2/datasets/${encodeURIComponent(id)}`,null,controller.signal);if(controller!==this.selectionController||!el('dialog').open)return;if(data.kind!==kind||!completed(data))throw new Error('Open a completed CT reconstruction. Resume incomplete jobs first.');this.manifest=data;this.view=null;el('saved-notes').hidden=true;el('cursor-position').textContent='Reading saved cursor…';el('cursor-attenuation').textContent='';el('cursor-coverage').textContent='';for(const plane of Object.keys(axes)){el(`${plane}-caption`).textContent='';const canvas=el(plane);canvas.getContext('2d').clearRect(0,0,canvas.width,canvas.height);canvas._ctPlot=null;delete canvas.dataset.rows;}for(const [axis,index] of [['x',2],['y',1],['z',0]]){this.cursor[`${axis}_index`]=Math.floor(data.shape[index]/2);el(axis).max=data.shape[index]-1;}el('dataset-name').textContent=data.name;el('dataset-detail').textContent=`${data.shape.join(' × ')} samples · Z, Y, X · attenuation in mm⁻¹${data.voxel_pitch_mm?` · pitch X/Y/Z ${data.voxel_pitch_mm.map(value=>fmt(value*1000)).join(' / ')} µm`:''}`;el('export').href=`/api/v2/datasets/${encodeURIComponent(id)}/export`;el('viewer').hidden=false;el('empty').hidden=true;const settings=data.reconstruction||data.request?.reconstruction||{};el('provenance').textContent=`CT dataset ${id}. Source projection dataset ${data.source_dataset_id||data.request?.source_dataset_id}. ${settings.filter} filter; cutoff ${settings.frequency_cutoff} of detector Nyquist. Zero-count policy: ${settings.invalid_policy}. Truncation policy: ${settings.truncation_policy}. Synthetic parallel-beam filtered backprojection; not experimentally calibrated or validated.`;try{localStorage.setItem('virtual-microscopy-last-ct',id);}catch{}this.renderCatalog();this.selecting=false;await this.loadView();}catch(error){if(error.name!=='AbortError')this.message(error.message,true);}finally{if(controller===this.selectionController){this.selecting=false;for(const axis of ['x','y','z'])el(axis).disabled=false;}}}
  viewSoon(){if(this.selecting)return;this.viewController?.abort();clearTimeout(this.viewTimer);this.viewTimer=setTimeout(()=>this.loadView(),90);}
  async loadView(){if(!this.manifest||!el('dialog').open)return;this.viewController?.abort();const controller=this.viewController=new AbortController(),id=this.manifest.dataset_id||this.manifest.id;el('view-note').textContent='Reading saved orthogonal slices…';try{const view=await this.request(`/api/v2/datasets/${encodeURIComponent(id)}/reconstruction-view?${new URLSearchParams(this.cursor)}`,null,controller.signal);if(controller!==this.viewController||id!==(this.manifest?.dataset_id||this.manifest?.id))return;this.view=view;for(const axis of ['x','y','z']){this.cursor[`${axis}_index`]=view.cursor[`${axis}_index`];el(axis).value=this.cursor[`${axis}_index`];el(`${axis}-value`).textContent=`${fmt(view.cursor[`${axis}_mm`])} mm`;}for(const [plane,normal] of [['xy','z'],['xz','y'],['yz','x']])el(`${plane}-caption`).textContent=`${normal.toUpperCase()} = ${fmt(view.cursor[`${normal}_mm`])} mm`;el('view-note').textContent='Reading saved data only. Moving the linked cursor or changing display limits does not rerun reconstruction.';el('cursor-position').textContent=`X ${fmt(view.cursor.x_mm)} / Y ${fmt(view.cursor.y_mm)} / Z ${fmt(view.cursor.z_mm)} mm`;el('cursor-attenuation').textContent=view.cursor.coverage<1-1e-6?`Attenuation masked · ${view.cursor.coverage>0?'partial':'no'} angular support`:`Attenuation ${fmt(view.cursor.attenuation)} mm⁻¹`;el('cursor-coverage').textContent=`Geometric angular support ${fmt(view.cursor.coverage*100)}%`;const warnings=view.metadata?.warnings||[];el('saved-notes').hidden=!warnings.length;el('saved-notes').querySelector('summary').textContent=`Saved reconstruction notes (${warnings.length})`;el('saved-notes').querySelector('ul').replaceChildren();for(const warning of warnings){const li=document.createElement('li');li.textContent=warning;el('saved-notes').querySelector('ul').append(li);}this.message('Saved CT volume ready. Click a section or use the arrow keys to move the linked physical cursor.');this.draw();}catch(error){if(error.name!=='AbortError'&&controller===this.viewController){this.message(`CT view unavailable: ${error.message}`,true);el('view-note').textContent='Requested view was not applied; the previous saved slices remain visible.';}}}
  draw(){if(!this.view||!el('dialog').open)return;for(const [plane,coordinates] of Object.entries(axes))drawSlice(el(plane),this.view[plane],coordinates,this.view.cursor,this.window);el('window-low').textContent=fmt(this.window[0]);el('window-high').textContent=fmt(this.window[1]);}
  pick(plane,event){const canvas=el(plane),plot=canvas._ctPlot;if(!plot||!this.view||this.selecting)return;const rect=canvas.getBoundingClientRect(),fx=(event.clientX-rect.left-plot.left)/plot.width,fy=(event.clientY-rect.top-plot.top)/plot.height;if(fx<0||fx>1||fy<0||fy>1)return;const [horizontal,vertical]=axes[plane];this.cursor[`${horizontal}_index`]=Math.min(plot.cols-1,Math.floor(fx*plot.cols));this.cursor[`${vertical}_index`]=Math.min(plot.rows-1,Math.floor(fy*plot.rows));this.viewSoon();}
  move(plane,event){if(!this.view||this.selecting||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();const horizontal=['ArrowLeft','ArrowRight'].includes(event.key),axis=axes[plane][horizontal?0:1],sign=['ArrowLeft','ArrowUp'].includes(event.key)?-1:1,max=this.manifest.shape[{x:2,y:1,z:0}[axis]]-1;this.cursor[`${axis}_index`]=Math.max(0,Math.min(max,this.cursor[`${axis}_index`]+sign*(event.shiftKey?10:1)));this.viewSoon();}
}

function drawSlice(canvas,data,axes,cursor,window){const width=canvas.clientWidth,height=canvas.clientHeight;if(!width||!height||!data?.image?.length)return;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.fillStyle='#fafcfd';ctx.fillRect(0,0,width,height);const rows=data.image.length,cols=data.image[0].length,off=document.createElement('canvas');off.width=cols;off.height=rows;const oc=off.getContext('2d'),pixels=oc.createImageData(cols,rows);for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const value=data.image[y][x],coverage=data.coverage?.[y]?.[x]??0,v=Math.round(Math.min(1,Math.max(0,(value-window[0])/(window[1]-window[0])))*255),i=(y*cols+x)*4;const rgb=!Number.isFinite(value)||coverage<=0?[90,103,116]:coverage<1-1e-6?[167,177,187]:[v,v,v];pixels.data.set([...rgb,255],i);}oc.putImageData(pixels,0,0);const left=59,top=14,w=width-left-20,h=height-top-41,[a0,a1,b0,b1]=data.extent_mm;ctx.imageSmoothingEnabled=false;ctx.drawImage(off,left,top,w,h);ctx.strokeStyle='#b6c8d8';ctx.strokeRect(left,top,w,h);ctx.font='10px "Segoe UI",sans-serif';ctx.fillStyle='#55718a';for(let i=0;i<=4;i++){const f=i/4;ctx.textAlign='center';ctx.fillText(fmt(a0+(a1-a0)*f),left+w*f,top+h+17);ctx.textAlign='right';ctx.fillText(fmt(b0+(b1-b0)*f),left-7,top+h*f+3);}ctx.textAlign='center';ctx.fillText(`${axes[0].toUpperCase()} (mm)`,left+w/2,height-3);ctx.save();ctx.translate(12,top+h/2);ctx.rotate(-Math.PI/2);ctx.fillText(`${axes[1].toUpperCase()} (mm)`,0,0);ctx.restore();const x=left+(cursor[`${axes[0]}_mm`]-a0)/(a1-a0)*w,y=top+(cursor[`${axes[1]}_mm`]-b0)/(b1-b0)*h;ctx.strokeStyle='#28a9e5';ctx.setLineDash([5,3]);ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,top+h);ctx.moveTo(left,y);ctx.lineTo(left+w,y);ctx.stroke();ctx.setLineDash([]);canvas._ctPlot={left,top,width:w,height:h,rows,cols};canvas.dataset.rows=rows;canvas.dataset.columns=cols;}
