import './xray.css';

const el=id=>document.getElementById(`xpv-${id}`);
const fmt=n=>Number(n).toLocaleString(undefined,{maximumFractionDigits:3});
const bytes=n=>n>=1073741824?`${(n/1073741824).toFixed(2)} GiB`:n>=1048576?`${(n/1048576).toFixed(1)} MiB`:`${(n/1024).toFixed(1)} KiB`;
const field=(id,label,value,min,max,step='any')=>`<label for="xpv-${id}">${label}<input id="xpv-${id}" type="number" value="${value}" min="${min}" max="${max}" step="${step}" required></label>`;
const finished=m=>m.complete===true||m.state==='completed';
const active=status=>['queued','running','cancel_requested','cancelling','pending','resuming'].includes(status);
const kind='xray_projection_volume';

export class XrayWorkspace {
  constructor({request,getSnapshot}) {
    Object.assign(this,{request,getSnapshot});this.jobs=[];this.datasets=[];this.cursor={view_index:0,detector_row:0};this.product='transmission';this.windowMax=1;
    document.body.insertAdjacentHTML('beforeend',`
      <dialog id="xpv-dialog" aria-labelledby="xpv-title" aria-describedby="xpv-intro">
        <div class="xpv-header"><div><h2 id="xpv-title">X-ray projection volumes</h2><p id="xpv-intro">Saved parallel-beam projections across a full rotation. Synthetic measurements; reconstruction comes later.</p></div><button id="xpv-close" class="quiet" aria-label="Close X-ray volumes">✕</button></div>
        <div class="xpv-layout">
          <aside class="xpv-acquisition" aria-label="X-ray acquisition and saved datasets">
            <details id="xpv-new-panel" open><summary>New projection acquisition</summary><p id="xpv-snapshot" class="xpv-snapshot"></p><button id="xpv-refresh-snapshot" class="small">Use current digital twin</button>
              <form id="xpv-form">
                <fieldset><legend>Source & detector response</legend><div class="xpv-fields">${field('energy_kev','Photon energy (keV)',80,40,150)}${field('photons','Photons per pixel',50000,1000,1000000,1)}${field('seed','Noise seed',42,0,4294967295,1)}${field('detector_fwhm_mm','Detector blur FWHM (mm)',.02,0,1)}</div><label class="xpv-check"><input id="xpv-noise" type="checkbox">Seeded Poisson counting noise</label><p class="xpv-hint">Monoenergetic source. Photon energy is not tube kVp.</p></fieldset>
                <fieldset><legend>Rotation around Y</legend><div class="xpv-fields">${field('views','Views',72,1,720,1)}${field('angle_start_deg','Start angle (°)',0,-360,360)}${field('angle_span_deg','Angular span (°)',360,.001,360)}</div><p id="xpv-angles-note" class="xpv-hint">The final endpoint is excluded; a 360° acquisition does not duplicate the first view.</p></fieldset>
                <fieldset><legend>Independent spatial sampling</legend><div class="xpv-fields">${field('geometry_nx','Geometry X cells',96,16,256,1)}${field('geometry_ny','Geometry Y cells',96,16,256,1)}${field('geometry_nz','Geometry Z cells',256,32,1024,1)}${field('detector_cols','Detector columns',96,16,256,1)}${field('detector_rows','Detector rows',64,16,256,1)}</div><p class="xpv-hint">Material-grid spacing and detector pitch are independent. Neither is a claim of instrument resolution.</p></fieldset>
                <fieldset><legend>Detector coverage & rotation center</legend><label class="xpv-check"><input id="xpv-auto-detector" type="checkbox" checked>Automatic field size before offsets</label><div class="xpv-fields">${field('detector_width_mm','Detector width (mm)',60,.05,300)}${field('detector_height_mm','Detector height (mm)',60,.05,300)}${field('detector_offset_u_mm','Detector U offset (mm)',0,-100,100)}${field('detector_offset_v_mm','Detector V offset (mm)',0,-100,100)}${field('center_x','Rotation center X (mm)',30,0,100)}${field('center_y','Rotation center Y (mm)',30,0,100)}${field('center_z','Rotation center Z (mm)',1.325,0,100)}</div><p class="xpv-hint">U/V are local detector coordinates. Offsets move the detector plane; they do not turn detector pixels into specimen points.</p></fieldset>
                <div id="xpv-estimate" class="xpv-estimate" aria-live="polite">Estimating resources…</div><details id="xpv-warnings" hidden><summary>Sampling and model notes</summary><ul></ul></details><button id="xpv-estimate-btn" class="small" type="button">Estimate resources</button><button id="xpv-start" class="primary" type="submit" disabled>Start X-ray acquisition</button>
              </form>
            </details>
            <section class="xpv-jobs"><h3>X-ray jobs</h3><div id="xpv-jobs-list"></div></section>
            <section class="xpv-saved"><div class="xpv-list-heading"><h3>Saved projections</h3><button id="xpv-refresh-list" class="quiet" aria-label="Refresh saved X-ray datasets">↻</button></div><div id="xpv-datasets"></div></section>
          </aside>
          <main class="xpv-inspector">
            <div id="xpv-message" class="xpv-message" role="status" aria-live="polite">Projection views and sinograms read saved data.</div>
            <div id="xpv-empty" class="xpv-empty"><svg viewBox="0 0 150 105" fill="none" aria-hidden="true"><path d="M14 20h29m-29 20h29m-29 20h29m-29 20h29M121 13v75"/><rect x="61" y="30" width="30" height="40"/><path d="m71 14 9-6 7 6m-7-6v17M49 34l-6 6 6 6M111 59l7-6-7-6"/></svg><h3>Rotate the virtual instrument around the full specimen</h3><p>Save counts, transmission, line integrals and validity masks with every source/detector pose. Inspect each projection or a detector-row sinogram without rerunning the projector.</p><p class="xpv-hint">This is a projection stack indexed by angle, detector V and detector U. It is not an XYZ reconstruction.</p></div>
            <div id="xpv-viewer" hidden>
              <div class="xpv-dataset-heading"><div><h3 id="xpv-dataset-name"></h3><p id="xpv-dataset-detail"></p></div><a id="xpv-export" class="xpv-download" href="#" download>Download Zarr archive</a></div>
              <div class="xpv-controls"><label for="xpv-view">Projection view <output id="xpv-angle-value"></output><input id="xpv-view" type="range" min="0" max="0" step="1" value="0"></label><label for="xpv-row">Detector row <output id="xpv-row-value"></output><input id="xpv-row" type="range" min="0" max="0" step="1" value="0"></label><label for="xpv-product">Saved product<select id="xpv-product"><option value="transmission">Transmission I / I₀</option><option value="line_integrals">Line integral −ln(I / I₀)</option><option value="counts">Photon counts</option></select></label><label for="xpv-window">Display maximum<input id="xpv-window" type="number" min="0.000001" step="any" value="1"></label></div>
              <p id="xpv-view-note" class="xpv-view-note">Reading saved detector data only.</p>
              <div class="xpv-map-grid"><section class="xpv-plot"><div><h4>Detector projection</h4><span id="xpv-projection-caption"></span></div><canvas id="xpv-projection" tabindex="0" role="img" aria-label="X-ray detector projection; click to choose a detector row"></canvas></section><section class="xpv-plot"><div><h4>Selected detector-row sinogram</h4><span id="xpv-sinogram-caption"></span></div><canvas id="xpv-sinogram" tabindex="0" role="img" aria-label="Saved sinogram indexed by angle and detector U; click to choose an acquired view"></canvas></section></div>
              <div class="xpv-lower"><section class="xpv-profile"><div><h4>Intensity across the selected row</h4><span id="xpv-profile-unit"></span></div><canvas id="xpv-profile" role="img" aria-label="Quantitative saved detector-row profile"></canvas></section><section class="xpv-geometry"><h4>Parallel-ray orientation</h4><canvas id="xpv-pose" role="img" aria-label="X-Z orientation diagram showing the parallel source, detector and Y rotation axis"></canvas><p id="xpv-pose-detail"></p></section></div>
              <div class="xpv-legend"><span>0</span><i></i><output id="xpv-window-value">1</output><span id="xpv-unit"></span><span class="xpv-invalid"><b></b>Undefined log at zero counts</span></div><p id="xpv-invalid-count" class="xpv-hint"></p><p id="xpv-provenance" class="xpv-hint"></p>
            </div>
          </main>
        </div>
      </dialog>`);
    el('close').addEventListener('click',()=>el('dialog').close());
    el('dialog').addEventListener('close',()=>{for(const key of ['pollTimer','estimateTimer','viewTimer'])clearTimeout(this[key]);for(const key of ['catalogController','selectionController','viewController','estimateController'])this[key]?.abort();});
    el('refresh-snapshot').addEventListener('click',()=>this.capture());el('form').addEventListener('input',()=>this.changed());el('estimate-btn').addEventListener('click',()=>this.estimate());el('form').addEventListener('submit',event=>{event.preventDefault();this.start();});el('refresh-list').addEventListener('click',()=>this.catalog());
    el('view').addEventListener('input',event=>{this.cursor.view_index=Number(event.target.value);this.viewSoon();});el('row').addEventListener('input',event=>{this.cursor.detector_row=Number(event.target.value);this.viewSoon();});
    el('product').addEventListener('change',event=>{this.product=event.target.value;this.defaultWindow();this.viewSoon();});el('window').addEventListener('input',()=>{const value=Number(el('window').value);if(value>0&&Number.isFinite(value)){this.windowMax=value;this.draw();}});
    for(const id of ['projection','sinogram']){el(id).addEventListener('click',event=>this.pick(id,event));el(id).addEventListener('keydown',event=>{if(!this.manifest||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(event.key))return;event.preventDefault();const key=id==='projection'?'detector_row':'view_index',max=this.manifest.shape[id==='projection'?1:0]-1,sign=['ArrowUp','ArrowLeft'].includes(event.key)?-1:1;this.cursor[key]=Math.max(0,Math.min(max,this.cursor[key]+sign*(event.shiftKey?10:1)));this.viewSoon();});}
    new ResizeObserver(()=>this.draw()).observe(document.querySelector('.xpv-inspector'));
  }
  message(text,error=false){el('message').textContent=text;el('message').classList.toggle('error',error);}
  open(){if(el('dialog').open)return;el('dialog').showModal();this.capture();this.catalog();requestAnimationFrame(()=>this.draw());}
  capture(){const snapshot=this.getSnapshot();if(!snapshot?.twin){this.message('Load a digital twin first.',true);return;}this.snapshot=structuredClone(snapshot);const s=snapshot.settings || {},size=snapshot.twin.size_mm;for(const [key,fallback] of [['energy_kev',80],['photons',50000],['seed',42]])el(key).value=s[key]??fallback;el('noise').checked=s.noise??true;for(const [axis,i] of [['x',0],['y',1],['z',2]]){el(`center_${axis}`).value=size[i]/2;el(`center_${axis}`).max=size[i];}el('detector_width_mm').value=Math.hypot(size[0],size[2]);el('detector_height_mm').value=size[1];el('snapshot').textContent=`${snapshot.twin.name}. Full specimen ${size.map(fmt).join(' × ')} mm retained for every projection. ${s.roi_mm?'The acoustic ROI does not crop X-ray ray paths. ':''}Embedded defects ${s.include_defects===false?'excluded':'included'}.`;this.changed();}
  acquisition(){const keys=['energy_kev','photons','seed','detector_fwhm_mm','views','angle_start_deg','angle_span_deg','geometry_nx','geometry_ny','geometry_nz','detector_cols','detector_rows','detector_offset_u_mm','detector_offset_v_mm'];return {...Object.fromEntries(keys.map(key=>[key,Number(el(key).value)])),noise:el('noise').checked,include_defects:this.snapshot.settings?.include_defects!==false,rotation_center_mm:['x','y','z'].map(axis=>Number(el(`center_${axis}`).value)),...(!el('auto-detector').checked?{detector_width_mm:Number(el('detector_width_mm').value),detector_height_mm:Number(el('detector_height_mm').value)}:{})};}
  payload(){return {kind,twin:this.snapshot.twin,acquisition:this.acquisition()};}
  changed(){this.estimateKey=null;el('start').disabled=true;this.estimateController?.abort();clearTimeout(this.estimateTimer);for(const id of ['detector_width_mm','detector_height_mm'])el(id).disabled=el('auto-detector').checked;const count=Number(el('views').value),start=Number(el('angle_start_deg').value),span=Number(el('angle_span_deg').value);el('angles-note').textContent=count===1?`One view at ${fmt(start)}°. This provides no angular sampling.`:`${fmt(span/count)}° steps; acquired angles ${fmt(start)}° to ${fmt(start+span*(count-1)/count)}°. Final endpoint excluded.`;el('estimate').textContent='Settings changed. Estimating resource use…';this.estimateTimer=setTimeout(()=>this.estimate(),350);}
  async estimate(){clearTimeout(this.estimateTimer);if(!this.snapshot||!el('dialog').open)return;if(!el('form').checkValidity()){el('estimate').textContent='Correct the acquisition fields before estimating.';return;}const body=this.payload(),key=JSON.stringify(body);this.estimateController?.abort();const controller=this.estimateController=new AbortController();el('start').disabled=true;
    try{const result=await this.request('/api/v2/estimate',body,controller.signal);if(controller!==this.estimateController||key!==JSON.stringify(this.payload()))return;this.estimateKey=key;if(el('auto-detector').checked)for(const id of ['detector_width_mm','detector_height_mm'])if(Number.isFinite(result[id]))el(id).value=result[id];el('estimate').textContent=`${result.shape.join(' × ')} samples (view, V, U). Stored products: ${bytes(result.total_bytes)}. Estimated peak memory: ${bytes(result.estimated_peak_bytes)}.${result.free_disk_bytes!==undefined?` Disk available: ${bytes(result.free_disk_bytes)}.`:''}${result.geometry_pitch_um?` Geometry pitch X/Y/Z: ${result.geometry_pitch_um.map(fmt).join(' / ')} µm.`:''}${result.detector_pixel_pitch_um?` Detector pitch U/V: ${result.detector_pixel_pitch_um.map(fmt).join(' / ')} µm.`:''}`;el('warnings').hidden=!result.warnings?.length;el('warnings').querySelector('ul').replaceChildren();for(const warning of result.warnings || []){const li=document.createElement('li');li.textContent=warning;el('warnings').querySelector('ul').append(li);}el('start').disabled=Boolean(this.starting);}
    catch(error){if(error.name!=='AbortError'&&controller===this.estimateController){this.estimateKey=null;el('estimate').textContent=error.message;}}
  }
  async start(){if(this.starting||!el('form').reportValidity())return;const body=this.payload();if(this.estimateKey!==JSON.stringify(body)){await this.estimate();if(this.estimateKey!==JSON.stringify(body))return;}this.starting=true;el('start').disabled=true;el('start').textContent='Submitting…';try{const job=await this.request('/api/v2/jobs',body);this.pendingId=job.dataset_id;el('new-panel').open=false;this.message('X-ray acquisition submitted. The full specimen, settings and every detector pose are frozen with this dataset.');await this.catalog();}catch(error){this.message(error.message,true);}finally{this.starting=false;el('start').textContent='Start X-ray acquisition';el('start').disabled=!this.estimateKey;}}
  async catalog(){clearTimeout(this.pollTimer);this.catalogController?.abort();const controller=this.catalogController=new AbortController();try{const [jobs,data]=await Promise.all([this.request('/api/v2/jobs',null,controller.signal),this.request('/api/v2/datasets',null,controller.signal)]);if(controller!==this.catalogController)return;this.jobs=jobs.jobs.filter(j=>j.kind===kind);this.datasets=data.datasets.filter(d=>d.kind===kind);this.renderCatalog();const pending=this.datasets.find(d=>(d.dataset_id || d.id)===this.pendingId&&finished(d));if(pending){this.pendingId=null;await this.select(pending.dataset_id || pending.id);}else if(!this.manifest){let saved;try{saved=localStorage.getItem('virtual-microscopy-last-xray');}catch{}const found=this.datasets.find(d=>finished(d)&&(d.dataset_id || d.id)===saved)||this.datasets.find(finished);if(found)await this.select(found.dataset_id || found.id);}}
    catch(error){if(error.name!=='AbortError')this.message(`X-ray catalog unavailable: ${error.message}`,true);}finally{if(controller===this.catalogController&&el('dialog').open)this.pollTimer=setTimeout(()=>this.catalog(),this.jobs.some(j=>active(j.status))?1200:6000);}}
  renderCatalog(){const order=list=>[...list].sort((a,b)=>String(b.created_at || '').localeCompare(a.created_at || ''));const signature=JSON.stringify([this.jobs,this.datasets,this.manifest?.dataset_id]);if(signature===this.catalogSignature)return;this.catalogSignature=signature;el('jobs-list').replaceChildren();el('datasets').replaceChildren();
    if(!this.jobs.length)el('jobs-list').textContent='No X-ray acquisition jobs yet.';
    for(const job of order(this.jobs).slice(0,8)){const row=document.createElement('div');row.className='xpv-job';row.dataset.jobId=job.id;const title=document.createElement('strong'),done=job.completed_units ?? job.completed_rows ?? 0,total=job.total_units ?? job.total_rows ?? 1;title.textContent=`${job.status.replaceAll('_',' ')} · ${done}/${total} views`;const progress=document.createElement('progress');progress.max=total;progress.value=done;progress.setAttribute('aria-label',`X-ray job ${job.id} progress`);row.append(title,progress);if(job.error){const error=document.createElement('p');error.textContent=job.error;row.append(error);}const action=active(job.status)?'cancel':['cancelled','interrupted','failed'].includes(job.status)?'resume':null;if(action){const button=document.createElement('button');button.className='small';button.textContent=action==='cancel'?'Cancel acquisition':'Resume acquisition';button.dataset.action=action;button.addEventListener('click',async()=>{button.disabled=true;try{const result=await this.request(`/api/v2/jobs/${encodeURIComponent(job.id)}/${action}`,{});if(action==='resume')this.pendingId=result.dataset_id;this.message(action==='cancel'?'Cancellation requested. Completed views remain saved.':'Resuming the saved acquisition.');await this.catalog();}catch(error){button.disabled=false;this.message(error.message,true);}});row.append(button);}el('jobs-list').append(row);}
    if(!this.datasets.length)el('datasets').textContent='No saved X-ray projection stacks.';
    for(const data of order(this.datasets)){const id=data.dataset_id || data.id,button=document.createElement('button');button.className='xpv-dataset';button.dataset.datasetId=id;button.disabled=!finished(data);button.setAttribute('aria-pressed',String(id===(this.manifest?.dataset_id || this.manifest?.id)));for(const [tag,text] of [['strong',data.name],['span',`${data.shape.join(' × ')} · ${data.state}`],['span',`${new Date(data.created_at).toLocaleString()} · ${id.slice(0,8)}`]]){const child=document.createElement(tag);child.textContent=text;button.append(child);}button.addEventListener('click',()=>this.select(id));el('datasets').append(button);}}
  async select(id){this.selectionController?.abort();this.viewController?.abort();const controller=this.selectionController=new AbortController();this.selecting=true;el('view-note').textContent='Opening saved X-ray dataset…';for(const id of ['view','row','product'])el(id).disabled=true;
    try{const data=await this.request(`/api/v2/datasets/${encodeURIComponent(id)}`,null,controller.signal);if(controller!==this.selectionController||!el('dialog').open)return;if(data.kind!==kind)throw new Error('This dataset belongs to another microscope. Open it in the matching workspace.');if(!finished(data))throw new Error('Resume this incomplete acquisition before inspecting its numerical views.');this.manifest=data;this.view=null;for(const canvas of el('viewer').querySelectorAll('canvas')){canvas.getContext('2d').clearRect(0,0,canvas.width,canvas.height);canvas._xrayPlot=null;delete canvas.dataset.rows;}this.cursor={view_index:0,detector_row:Math.floor(data.shape[1]/2)};el('view').max=data.shape[0]-1;el('row').max=data.shape[1]-1;el('dataset-name').textContent=data.name;el('dataset-detail').textContent=`${data.shape.join(' × ')} samples · view, detector V, detector U · ${new Date(data.created_at).toLocaleString()}`;el('export').href=`/api/v2/datasets/${encodeURIComponent(id)}/export`;this.defaultWindow();el('empty').hidden=true;el('viewer').hidden=false;el('provenance').textContent=`Dataset ${id}. Synthetic monoenergetic parallel-beam acquisition. Full specimen and frozen poses are included in the archive. No scatter, beam hardening or CT reconstruction. Detector pixels integrate paths through the specimen and do not identify unique XYZ points. Cropping the detector does not refine the full-specimen material grid.`;try{localStorage.setItem('virtual-microscopy-last-xray',id);}catch{}this.renderCatalog();this.selecting=false;await this.loadView();}
    catch(error){if(error.name!=='AbortError')this.message(error.message,true);}finally{if(controller===this.selectionController){this.selecting=false;for(const id of ['view','row','product'])el(id).disabled=false;}}}
  defaultWindow(){this.windowMax=this.product==='counts'?(this.manifest?.acquisition?.photons || 50000):this.product==='line_integrals'?4:1;el('window').value=this.windowMax;}
  viewSoon(){if(this.selecting)return;this.viewController?.abort();clearTimeout(this.viewTimer);this.viewTimer=setTimeout(()=>this.loadView(),90);}
  async loadView(){if(!this.manifest||!el('dialog').open)return;this.viewController?.abort();const controller=this.viewController=new AbortController(),id=this.manifest.dataset_id || this.manifest.id;el('view-note').textContent='Reading saved projections and detector-row sinogram…';const query=new URLSearchParams({...this.cursor,product:this.product});
    try{const view=await this.request(`/api/v2/datasets/${encodeURIComponent(id)}/xray-view?${query}`,null,controller.signal);if(controller!==this.viewController||id!==(this.manifest?.dataset_id || this.manifest?.id))return;this.view=view;this.viewProduct=view.product || this.product;this.cursor={view_index:view.cursor.view_index,detector_row:view.cursor.detector_row};el('view').value=this.cursor.view_index;el('row').value=this.cursor.detector_row;el('angle-value').textContent=`${fmt(view.cursor.angle_deg)}° · ${view.cursor.view_index+1}/${this.manifest.shape[0]}`;el('row-value').textContent=`V = ${fmt(view.cursor.v_mm)} mm`;el('projection-caption').textContent=`${fmt(view.cursor.angle_deg)}° · ${view.projection.unit}`;el('sinogram-caption').textContent=this.manifest.shape[0]===1?'One acquired angle; no angular information between views':`V = ${fmt(view.cursor.v_mm)} mm`;el('profile-unit').textContent=view.profile.unit;el('unit').textContent=view.projection.unit;el('view-note').textContent='Reading saved data only. Scrubbing views, changing detector row or switching saved products does not rerun the projector.';el('invalid-count').textContent=`${view.invalid_pixels ?? 0} zero-count pixels in this projection; their logarithms are undefined. Raw counts and transmission zeros remain valid. Display values clip to 0–${fmt(this.windowMax)}; saved arrays retain their numerical values.`;this.message('Saved X-ray volume ready. Select a view or detector row to inspect the recorded data.');this.draw();}
    catch(error){if(error.name!=='AbortError'&&controller===this.viewController){this.message(`View unavailable: ${error.message}`,true);el('view-note').textContent='Requested view was not applied; the previous saved view is retained.';}}}
  draw(){if(!this.view||!el('dialog').open)return;const view=this.view;drawImage(el('projection'),view.projection,['Detector U (mm)','Detector V (mm)'],this.windowMax,this.viewProduct==='line_integrals'?view.projection.invalid_mask:null,view.cursor.v_mm);drawImage(el('sinogram'),view.sinogram,['Detector U (mm)','Acquisition angle (°)'],this.windowMax,this.viewProduct==='line_integrals'?view.sinogram.invalid_mask:null,view.cursor.angle_deg);drawProfile(el('profile'),view.profile,this.windowMax,this.viewProduct==='line_integrals');drawPose(el('pose'),view.pose,this.manifest.request?.twin?.size_mm || this.snapshot?.twin?.size_mm,view.cursor.angle_deg,this.manifest.acquisition?.rotation_center_mm);el('pose-detail').textContent=`Ray direction [${view.pose.ray_direction_xyz.map(fmt).join(', ')}]. Detector center [${view.pose.detector_center_mm.map(fmt).join(', ')}] mm. Schematic distances and offsets; source rays are parallel. The saved detector center defines a virtual reference plane.`;el('window-value').textContent=fmt(this.windowMax);el('invalid-count').textContent=`${view.invalid_pixels ?? 0} zero-count pixels in this projection; their logarithms are undefined. Raw counts and transmission zeros remain valid. Display values clip to 0–${fmt(this.windowMax)}; saved arrays retain their numerical values.`;}
  pick(id,event){const canvas=el(id),plot=canvas._xrayPlot;if(!plot||!this.view)return;const bounds=canvas.getBoundingClientRect(),f=(event.clientY-bounds.top-plot.top)/plot.height;if(f<0||f>1||event.clientX-bounds.left<plot.left||event.clientX-bounds.left>plot.left+plot.width)return;if(id==='projection')this.cursor.detector_row=Math.min(this.manifest.shape[1]-1,Math.floor(f*this.manifest.shape[1]));else{const angles=this.view.sinogram.angles_deg || this.manifest.angles_deg,value=plot.extent[2]+f*(plot.extent[3]-plot.extent[2]);this.cursor.view_index=angles.reduce((best,angle,index)=>Math.abs(angle-value)<Math.abs(angles[best]-value)?index:best,0);}this.viewSoon();}
}

function canvasContext(canvas){const width=canvas.clientWidth,height=canvas.clientHeight;if(!width||!height)return null;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.fillStyle='#fafcfd';ctx.fillRect(0,0,width,height);ctx.font='10px "Segoe UI",sans-serif';return {ctx,width,height,dpr};}
function drawImage(canvas,data,axes,max,invalid,line){const s=canvasContext(canvas);if(!s||!data?.image?.length)return;const {ctx,width,height}=s,rows=data.image.length,cols=data.image[0].length,off=document.createElement('canvas');off.width=cols;off.height=rows;const oc=off.getContext('2d'),pixels=oc.createImageData(cols,rows);for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const value=data.image[y][x],bad=invalid?.[y]?.[x]||!Number.isFinite(value),v=Math.round(Math.min(1,Math.max(0,value/max))*255),i=(y*cols+x)*4;pixels.data[i]=bad?131:v;pixels.data[i+1]=bad?140:v;pixels.data[i+2]=bad?150:v;pixels.data[i+3]=255;}oc.putImageData(pixels,0,0);const left=57,top=13,w=width-left-19,h=height-top-39,extent=data.extent_mm || data.extent,[u0,u1,v0,v1]=extent;ctx.imageSmoothingEnabled=false;ctx.drawImage(off,left,top,w,h);ctx.strokeStyle='#b4c5d4';ctx.strokeRect(left,top,w,h);ctx.fillStyle='#587086';for(let i=0;i<=4;i++){const f=i/4;ctx.textAlign='center';ctx.fillText(fmt(u0+(u1-u0)*f),left+w*f,top+h+17);ctx.textAlign='right';ctx.fillText(fmt(v0+(v1-v0)*f),left-7,top+h*f+3);}ctx.textAlign='center';ctx.fillText(axes[0],left+w/2,height-3);ctx.save();ctx.translate(12,top+h/2);ctx.rotate(-Math.PI/2);ctx.fillText(axes[1],0,0);ctx.restore();if(Number.isFinite(line)){const y=top+(line-v0)/(v1-v0)*h;ctx.strokeStyle='#26adf1';ctx.setLineDash([4,3]);ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(left+w,y);ctx.stroke();ctx.setLineDash([]);}canvas._xrayPlot={left,top,width:w,height:h,extent};canvas.dataset.rows=rows;canvas.dataset.columns=cols;}
function drawProfile(canvas,data,max,maskInvalid){const s=canvasContext(canvas);if(!s||!data?.values?.length)return;const {ctx,width,height}=s,left=53,top=17,w=width-left-17,h=height-top-35,u=data.u_mm,x0=u[0],x1=u.at(-1);ctx.strokeStyle='#dce5ed';ctx.fillStyle='#5a738b';for(let i=0;i<=4;i++){const f=i/4;ctx.beginPath();ctx.moveTo(left,top+h*f);ctx.lineTo(left+w,top+h*f);ctx.stroke();ctx.textAlign='right';ctx.fillText(fmt(max*(1-f)),left-7,top+h*f+3);ctx.textAlign='center';ctx.fillText(fmt(x0+(x1-x0)*f),left+w*f,top+h+17);}ctx.save();ctx.beginPath();ctx.rect(left,top,w,h);ctx.clip();ctx.beginPath();let connected=false;data.values.forEach((value,i)=>{if(!Number.isFinite(value)||(maskInvalid&&data.invalid_mask?.[i])){connected=false;return;}const x=left+(u[i]-x0)/(x1-x0)*w,y=top+h-value/max*h;connected?ctx.lineTo(x,y):ctx.moveTo(x,y);connected=true;});ctx.strokeStyle='#247fad';ctx.lineWidth=1.5;ctx.stroke();ctx.restore();ctx.textAlign='center';ctx.fillText('Detector U (mm)',left+w/2,height-2);}
function drawPose(canvas,pose,size,angle,rotationCenter){const s=canvasContext(canvas);if(!s||!pose)return;const {ctx,width,height}=s,cx=width/2,cz=height/2+4,r=Math.min(width*.3,height*.35),d=pose.ray_direction_xyz,u=pose.detector_u_xyz;ctx.strokeStyle='#d6e1ea';ctx.beginPath();ctx.arc(cx,cz,r*.72,0,2*Math.PI);ctx.stroke();if(size){const scale=r*1.15/Math.hypot(size[0],size[2]),center=rotationCenter || size.map(value=>value/2);ctx.fillStyle='#e2ebf3';ctx.strokeStyle='#9fb3c8';ctx.fillRect(cx-center[0]*scale,cz-center[2]*scale,size[0]*scale,Math.max(2,size[2]*scale));ctx.strokeRect(cx-center[0]*scale,cz-center[2]*scale,size[0]*scale,Math.max(2,size[2]*scale));}const arrow=(x0,y0,x1,y1,color)=>{ctx.strokeStyle=color;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x0,y0);ctx.lineTo(x1,y1);ctx.stroke();const a=Math.atan2(y1-y0,x1-x0);ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x1-6*Math.cos(a-.4),y1-6*Math.sin(a-.4));ctx.lineTo(x1-6*Math.cos(a+.4),y1-6*Math.sin(a+.4));ctx.fill();};for(const offset of [-.32,0,.32])arrow(cx-d[0]*r+u[0]*r*offset,cz-d[2]*r+u[2]*r*offset,cx+d[0]*r*.9+u[0]*r*offset,cz+d[2]*r*.9+u[2]*r*offset,'#6babc8');const dx=cx+d[0]*r,dy=cz+d[2]*r;ctx.strokeStyle='#25597e';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(dx-u[0]*r*.55,dy-u[2]*r*.55);ctx.lineTo(dx+u[0]*r*.55,dy+u[2]*r*.55);ctx.stroke();ctx.lineWidth=1;ctx.fillStyle='#274967';ctx.textAlign='center';ctx.fillText('Parallel source',cx-d[0]*r,cz-d[2]*r-9);ctx.fillText('Detector',dx,dy+16);ctx.beginPath();ctx.arc(cx,cz,4,0,2*Math.PI);ctx.fill();ctx.fillText('Y rotation axis',cx,cz-12);ctx.textAlign='left';ctx.fillText('X →',10,14);ctx.fillText('Z ↓',10,29);ctx.textAlign='right';ctx.fillText(`${fmt(angle)}°`,width-10,14);}
